### ISSUE TITLE
Missing method for `Series`: `get_chunks`

### ISSUE THREAD

**Issue by Yunuuuu** [pola-rs/r-polars#1000]
I don't know how to deal with the rust function: `get_chunks`
https://github.com/pola-rs/polars/blob/main/py-polars/src/series/mod.rs#L673

**Comment by eitsupi** [comment]
Why do you need this functionality?
From the logs it, seems this was needed for Python's DataFrame interchange protocol, R has no such thing so I don't see the need for it.

**Comment by eitsupi** [comment]
You can do like this with nanoarrow:

```r
``` r
library(polars)

s = as_polars_series(1:3)
s2 = as_polars_series(4:6)

pl$concat(s, s2, rechunk = FALSE)$to_frame() |>
  nanoarrow::as_nanoarrow_array_stream() |>
  nanoarrow::collect_array_stream() |>
  lapply(\(x) as_polars_df(x)$to_series())
#> [[1]]
#> polars Series: shape: (3,)
#> Series: '' [i32]
#> [
#>  1
#>  2
#>  3
#> ]
#>
#> [[2]]
#> polars Series: shape: (3,)
#> Series: '' [i32]
#> [
#>  4
#>  5
#>  6
#> ]
```

<sup>Created on 2024-03-31 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
```

**Comment by Yunuuuu** [comment]
> Why do you need this functionality?

This would be useful if we want to do some operations together for several series (since `struct` cannot work well currently), we cannot use `mapply` to pass several series into a function.

```r
s <- as_polars_series(1:3)
s2 <- as_polars_series(4:6)

ss <- c(s, s2)
ss$map_batches(\(s) chunks <- ss$get_chunks()) # then do other operations
```

Thanks for your `nanoarrow` code, this may be a choice, I'll try it.

**Comment by eitsupi** [comment]
I am not sure. I think you are abusing about chunk splitting. Obviously it is not meant for that use.

Why not use DataFrame if you want to operate multiple Series?

``` r
library(polars)

s <- as_polars_series(1:3)
s2 <- as_polars_series(4:6)

pl$DataFrame(list(s, s2))$select(
  pl$all()$map_batches(\(x) {
    x$mul(2)
  })
)$get_columns()
#> [[1]]
#> polars Series: shape: (3,)
#> Series: '' [f64]
#> [
#>  2.0
#>  4.0
#>  6.0
#> ]
#>
#> [[2]]
#> polars Series: shape: (3,)
#> Series: '_1' [f64]
#> [
#>  8.0
#>  10.0
#>  12.0
#> ]
```

<sup>Created on 2024-04-01 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I think ChunkedArray's contents being multiple chuncks is a detail of the Apache Arrow implementation and not intended to be exposed to the user.

I'm closing this because I don't think there is a use case here.
