### ISSUE TITLE
if `saveRDS` can work for polars DataFrame?

### ISSUE THREAD

**Issue by Yunuuuu** [pola-rs/r-polars#1013]
I have used readRDS for DataFrame, but it return a `pointer`.  It's there a good way to save a list of `DataFrame` ?
```r
<pointer: (nil)>
attr(,"class")
[1] "RPolarsDataFrame"
```

**Comment by eitsupi** [comment]
In general, Rds files do not support external objects.
Use Parquet or Apache Arrow file format here.
