### ISSUE TITLE
Use the `testex` package for example testing

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#1017]
<https://github.com/dgkf/testex>

It may be unnecessary to copy the examples into `tests/`.

**Comment by etiennebacher** [comment]
I don't really see the usecase for this. Granted we usually copy examples in the test folder, but often we add additional tests that are not suitable for the examples so we'd have to add those examples in the test folder anyway. I'd rather keep all tests in the same place than having them scattered across several folders.

**Comment by etiennebacher** [comment]
I don't think we need this. I'm open to discuss more about this but for now I'd rather close to clean the issue tracker
