### ISSUE TITLE
Add support for Cloud parquet scanning

### ISSUE THREAD

**Issue by andyquinterom** [pola-rs/r-polars#1054]
Add support for cloud parquet scanning.

**Comment by etiennebacher** [comment]
#1056 added support for `storage_options` when reading/scanning parquet only. Other read/scan functions have this argument but sometimes one has it and not the other (e.g `read_csv()` has it but not `scan_csv()`) and when they have it, the description is different (e.g for [read_csv()](https://docs.pola.rs/py-polars/html/reference/api/polars.read_csv.html)).

Should this be closed?

**Comment by etiennebacher** [comment]
This issue is only about cloud Parquet scanning and this was enabled in #1056, so I'm closing to clean the issue tracker.
