### ISSUE TITLE
Error in `csv_reader()` when `infer_schema_length = "None"`

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#106]
Hi @sorhawell, thanks for this package! 

The argument `infer_schema_length` in (`lazy_`)`csv_reader()` seems to be broken when I specify "None":

``` r
library(rpolars)
packageVersion("rpolars")
#> [1] '0.4.7'

# make a test csv file
file_location <- tempfile(fileext = ".csv")
write.csv(mtcars, file_location)

# works fine
test <- csv_reader(file_location)

# error
csv_reader(file_location, infer_schema_length = "None")
#> Error in (function (path, sep, has_header, ignore_errors, skip_rows, n_rows, : 
#>  unable to convert R object to primitive
```

But I'm just starting with this package so maybe I missed something?

**Comment by sorhawell** [comment]
Hello @etiennebacher, welcome here :)

rpolars is still a young project, and we very much appreciate any such reporting as this one.

In general rpolars encode the py-polars equivalent None with a NULL

try with this

```R
csv_reader(file_location, infer_schema_length = NULL)
polars DataFrame: shape: (32, 12)
┌────────────────┬──────┬─────┬───────┬─────┬─────┬─────┬──────┬──────┐
│                ┆ mpg  ┆ cyl ┆ disp  ┆ ... ┆ vs  ┆ am  ┆ gear ┆ carb │
│ ---            ┆ ---  ┆ --- ┆ ---   ┆     ┆ --- ┆ --- ┆ ---  ┆ ---  │
│ str            ┆ f64  ┆ i64 ┆ f64   ┆     ┆ i64 ┆ i64 ┆ i64  ┆ i64  │
╞════════════════╪══════╪═════╪═══════╪═════╪═════╪═════╪══════╪══════╡
│ Mazda RX4      ┆ 21.0 ┆ 6   ┆ 160.0 ┆ ... ┆ 0   ┆ 1   ┆ 4    ┆ 4    │
│ Mazda RX4 Wag  ┆ 21.0 ┆ 6   ┆ 160.0 ┆ ... ┆ 0   ┆ 1   ┆ 4    ┆ 4    │
│ Datsun 710     ┆ 22.8 ┆ 4   ┆ 108.0 ┆ ... ┆ 1   ┆ 1   ┆ 4    ┆ 1    │
│ Hornet 4 Drive ┆ 21.4 ┆ 6   ┆ 258.0 ┆ ... ┆ 1   ┆ 0   ┆ 3    ┆ 1    │
│ ...            ┆ ...  ┆ ... ┆ ...   ┆ ... ┆ ... ┆ ... ┆ ...  ┆ ...  │
│ Ford Pantera L ┆ 15.8 ┆ 8   ┆ 351.0 ┆ ... ┆ 0   ┆ 1   ┆ 5    ┆ 4    │
│ Ferrari Dino   ┆ 19.7 ┆ 6   ┆ 145.0 ┆ ... ┆ 0   ┆ 1   ┆ 5    ┆ 6    │
│ Maserati Bora  ┆ 15.0 ┆ 8   ┆ 301.0 ┆ ... ┆ 0   ┆ 1   ┆ 5    ┆ 8    │
│ Volvo 142E     ┆ 21.4 ┆ 4   ┆ 121.0 ┆ ... ┆ 1   ┆ 1   ┆ 4    ┆ 2    │
└────────────────┴──────┴─────┴───────┴─────┴─────┴─────┴──────┴──────┘

```

**Comment by etiennebacher** [comment]
I see, thanks ;)

The docs should be updated then, currently they say:

> (NULL is disable) Maximum number of lines to read to infer schema. If set to 0, all columns will be read as pl.Utf8. If set to None, a full table scan will be done (slow).

Maybe this would be better:

> Maximum number of lines to read to infer the column types. If set to 0, all columns will be read as pl.Utf8. If NULL, a full table scan will be done (slow).

Also, could you return an error earlier by checking the type of this arg before calling the Rust function? In my case, the error could have been:

> Error: infer_schema_length must be an integer or NULL.

**Comment by sorhawell** [comment]
>Maybe this would be better: ...

You're right, I have copy pasted from py-polars docs too fast :)
Would you mind to submit a PR on this doc error?  :)

> checking the type of this arg before calling the Rust function? 
I have been pondering alot about what is the best approach. A given rust-polars method takes some rust types as input. If perming a succesful conversion from R to the rust type, most often there is no more to it. The macro robj_to! on rust side checks, and converts any R input to many rust types or return a useful error message explaining why a given argument is invalid.

read_csv should become more like scan_ipc

read_csv was some of the first I did. I will be upgraded to use robj_to! like in [scan_ipc](https://github.com/pola-rs/r-polars/blob/a4def1404a68c9c352bebd0763d42587eb69e8e5/src/rust/src/rdataframe/read_ipc.rs#L5) [and R side](https://github.com/pola-rs/r-polars/blob/a4def1404a68c9c352bebd0763d42587eb69e8e5/R/ipc.R)

**Comment by etiennebacher** [comment]
>  Would you mind to submit a PR on this doc error? :)

Sure, no problem 

> It is also ok to do checking some checking on R side, if that makes sense.

If using `robj_to!` on Rust side provides good error messages then I think it's enough

**Comment by etiennebacher** [comment]
Somehow, this time it got through (but I still have tons of message every time I recompile)

**Comment by sorhawell** [comment]
sorry about that it is this issue. It came with the latest new versions of R. I have to look into the linker docs and see if I can disable the warnings. Besides spamming your terminal, the warnings should be harmless.

https://github.com/pola-rs/r-polars/issues/93

@eitsupi wisely set up R Check workflow also to check against windows develop, such that I would have known of the up comming error early. Silly me thought we could cut down on the number of jobs running, and removed windows develop.
