### ISSUE TITLE
R-universe build missing?

### ISSUE THREAD

**Issue by grantmcdermott** [pola-rs/r-polars#110]
It might just be taking time to build the artifacts after the package rename (#84).

But from what I can tell, there's no actual CI build framework/action on the R-universe servers: https://github.com/orgs/r-universe/repositories?q=polars&type=all&sort=

Am I missing something obvious?

**Comment by sorhawell** [comment]
[yes we pressed the rename button today and crossed our fingers](https://github.com/r-universe-org/help/issues/28#issuecomment-1507682262)

We hope to fix it soon :)

**Comment by grantmcdermott** [comment]
Great, looks like the builds are working again. https://github.com/r-universe/rpolars/actions
