### ISSUE TITLE
set JEMALLOC on macos as well

### ISSUE THREAD

**Issue by ritchie46** [pola-rs/r-polars#1107]
We got an issue upstream that reported huge slowdowns. This was resolved by setting Jemalloc. I think it would be good to ship with Jemalloc for macos as well.

**Comment by eitsupi** [comment]
Thanks for pointing that!

I noticed this change was made in Python Polars today and made the change in 01860541d5b4ac674ba0bd3b58b65dbdb2f93021.
This should be included in the next release.
