### ISSUE TITLE
Potential improvements in tests?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#111]
Hi @sorhawell, I've been looking a bit at the test suite of `polars` (since I'm not good enough in Rust for now ;)) and I think there are some things there that could be improved. Below is a small list of potential improvements, I prefer posting here first so that (1) we can discuss some of these before spending too much time on this, and (2) other people can contribute to it.

- [x] improve the test coverage. Currently (on my Ubuntu laptop), `covr::report()` says that there is 23.96% of coverage (maybe the "weird" syntax of functions with dollars in name makes coverage detection harder, but my point is that not everything is covered). To me, this is the most important potential improvement but also the one that will take the most time.
- [x] use [snapshots](https://testthat.r-lib.org/articles/snapshotting.html) instead of manually hardcoded expectations. Below is an example of expectation that could be replaced by a snapshot so that it's easier to update if the formatting ever changes.
https://github.com/pola-rs/r-polars/blob/28c3cfeaa2d0834b41e4539e647acec2683a95a2/tests/testthat/test-dataframe.R#L12-L25
- [x] remove uses of `testthat::` (since `testthat` is automatically loaded by `devtools::load_all()`)
- [x] similarly, `polars:::` shouldn't be needed in tests because `devtools::load_all()` also loads internal functions for tests 
- [x] use more suited `expect_` functions, e.g replace `expect_identical(whatever, FALSE)` by `expect_false(whatever)` 
- [x] add some regex to `expect_error()` or `expect_warning()` (arg `regex`) to ensure that the message is really what we expect

There are maybe more but I didn't review all tests for now. As you can see, apart from increasing the coverage, most of these suggestions are here to make the tests easier to read and therefore reduce the cognitive load when something breaks.

Let me know what you think ;)

**Comment by sorhawell** [comment]
> says that there is 23.96% of coverage

I hoped we were in the >90% for public methods and functions. I suspect covr may include both e.g.
I rarely commit a method without an expectation

```R
polars:::wrap__Expr__abs
polars:::Expr_abs
Expr$abs
```

[The current public class methods and functions are about all these (except for sub namespaces):](https://rpolars.github.io/reference/pl.html)

I would be very useful with a covr workflow, and I do think we should aim for  100% coverage

**Comment by sorhawell** [comment]
> use more suited expect_ functions, e.g replace expect_identical(whatever, FALSE) by expect_false(whatever)

this one I agree with. How the majority of `expect_identical(x, y)` what do you recommend there?

**Comment by sorhawell** [comment]
> add some regex to expect_error() or expect_warning() (arg regex) to ensure that the message is really what we expect

This function is used here and there. `polars:::expect_grepl_error`.  Right now polars repeat in error message a given invalid call. This was very annoying to regex against. `expect_grepl_error` disables the call in error messages.

When ever changing error message form, it can be a big repetitive job to update the tests. I started to hold a bit back on testing any error message manually, but just some. All error messages conversions via the rust macro robj_to! does not need to be retested for every method.

this summer @Sicheng-Pan may look into reworking errors into being classed for more elegant error checking. 

I think I could need some inspiration :) how about you commit handful of updates as you see best, and then I can learn from you.

**Comment by sorhawell** [comment]
@etiennebacher  on a sidenote: @eitsupi  mentioned you have made [altdoc](https://github.com/etiennebacher/altdoc). I would really like to hear your view on documentation of methods e.g. as in https://rpolars.github.io/reference/index.html . Many in the extendr community are missing good ways to document and bundle methods by classes. Having all methods on the same class page is a bit messy, I think.

I think the py-polars reference layout is alright
https://pola-rs.github.io/polars/py-polars/html/reference/

**Comment by etiennebacher** [comment]
> I hoped we were in the >90% for public methods and functions. I suspect covr may include both e.g. I rarely commit a method without an expectation
>
> It would be very useful with a covr workflow, and I do think we should aim for 100% coverage
> 
> how do I get missed coverage best? covr::report() ?

Not sure, I used `covr::report()` but as you say it probably underestimated the coverage, I'll take a look soon

> I think I could need some inspiration :) how about you commit handful of updates as you see best, and then I can learn from you.

This is maybe the easiest way, I'll try to clean a few tests files so you can have more examples and see if we should expand it to the full test suite

> I would really like to hear your view on documentation of methods

I'm not sure `altdoc` would solve the problem. It only allows to use other documentation generators but in the end the structure of the functions reference is based on the `.Rd` files (more specifically I convert those Rd files to markdown) so I think the question of how to structure classes lies at a lower level. I remember some discussion about `R6` handling (which is maybe close to `polars` structure) in https://github.com/r-lib/roxygen2/issues but I don't remember where specifically.

Also, I'd be glad to see `altdoc` used in a popular project but to be honest `pkgdown` is 100x more maintained and more reliable.

**Comment by sorhawell** [comment]
@etiennebacher  did you mention somewhere that CRAN check locally is slow?

CRAN cmd checks tries really hard to avoid caching. Recompiling for every check is not fun

you can use  a snippet like this to check cached compilation. A full check takes then 1-2 min to run. 
```R
{devtools::check(env_vars = list(RPOLARS_RUST_SOURCE="/Users/sorenwelling/Documents/projs/v-polars/src/rust"),check_dir = "./check/",vignettes = FALSE);source("./inst/misc/filter_rcmdcheck.R"); Sys.sleep(5); unlink("check",recursive = TRUE)}
```

**Comment by etiennebacher** [comment]
Yes, I mentioned it in a PR, thanks a lot! When I recompile I still have the same issue as #93 though

**Comment by eitsupi** [comment]
Sorry, but due to the change in the print results, some of the tests will be changed to snapshot tests in #133.

**Comment by sorhawell** [comment]
The snippet should filter the error and finally state "you deserve a gold medal" right?
https://github.com/pola-rs/r-polars/blob/main/inst/misc/filter_rcmdcheck.R

My old windows desktop is struggling, when I get hold on another PC next week, I will try to fiddle with the windows linker.
