### ISSUE TITLE
Demo of mkdocs-material documentation

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#114]
Follow-up on https://github.com/pola-rs/r-polars/issues/111#issuecomment-1507944797 about documentation.

I made a small example of what the documentation could look like if it was made with Mkdocs-material. I think it would make it easier to classify functions by "general class" (DataFrame, Series, etc.) like `py-polars` does:

* repo: https://github.com/etiennebacher/testRTD
* demo: https://etiennebacher.github.io/testRTD/site

Of course, it's a super minimal example (don't pay attention to whether the docs are good or not, it's just a placeholder). I put some challenges and things to know in the README so you know the pros and cons.

**Comment by sorhawell** [comment]
@etiennebacher  This is very interesting. If the left class-viewer pane was locked on as default, then it would be home-run, in my mind.

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/8015271/232255096-9ea716a9-a834-44c2-bfb0-1e589ada6076.png">

This seems potentially compatible with vanilla-extendr also. A better method viewer is wanted in the extendr-community, I will pitch your demo on their discord, and get their feedback also :)

**Comment by etiennebacher** [comment]
> If the left class-viewer pane was locked on as default, then it would be home-run, in my mind.

I'm not sure what you mean but since it is mkdocs there are a ton of options and extensions available so I'm sure what you have in mind in possible.

Note that the "Home" and "Reference" can also be a separate tabs instead of being in the same sidebar

**Comment by etiennebacher** [comment]
I'm trying to understand more the code organization in `polars` so that I can make a more realistic example for the docs. Most functions in `dataframe__frame.R` are something like:
```r
DataFrame_shape = method_as_property(function() {
  .pr$DataFrame$shape(self)
})
```
The user never directly calls `DataFrame_shape()`, so this function definition is only here to generate `pkgdown`-compatible docs, right? I'm asking because if we could document  `DataFrame$shape()` directly, there would be no need to for the `method_as_property()` call above so this would simplify the codebase a lot.

**Comment by vincentarelbundock** [comment]
> The user never directly calls `DataFrame_shape()`, so this function definition is only here to generate `pkgdown`-compatible docs, right?

@etiennebacher Consider this code:

```r
library(polars)
dat = pl$DataFrame(mtcars)

dat$tail()
```

In this example, the user has called the `$tail()` method. However, internally in `polars`, that method is called `DataFrame_tail()` *and it is documented there*. The user needs to do this to access the docs:

```r
?DataFrame_tail()
```

So the documentation website would need to include all the `DataFrame_*()`, `Series_*()`, `Expr_*()` functions, and it would need to say very prominently to users that those correspond to methods accessible via `$` without the prefix.

Maybe even better would be to display each method in sections, such that the `DataFrame_tail` method would be in the `DataFrame` section, but only displayed as `tail`.

**Comment by etiennebacher** [comment]
Thanks for the explanation @vincentarelbundock 

> Maybe even better would be to display each method in sections, such that the DataFrame_tail method would be in the DataFrame section, but only displayed as tail.

I agree and it's not hard to do manually. A current issue with the docs is that the "Usage" section shows `DataFrame_<fn>()` while the user doesn't actually call this directly:

![image](https://user-images.githubusercontent.com/52219252/232403433-a3913d0d-03fc-46a7-827e-380c08734061.png)

One way to overcome this is to manually add a @usage section in the roxygen docs such as:

```r
#' @usage <DataFrame>$dtypes()
```
so that we know that this function can be chained to a DataFrame object. 

@sorhawell is this what you had in mind?

https://user-images.githubusercontent.com/52219252/232405570-5c3c875e-078e-45b1-b35e-943c340efd92.mp4

**Comment by sorhawell** [comment]
> One way to overcome this is to manually add a @usage section in the roxygen docs such as:
#' @usage <DataFrame>$dtypes()

I tried many times fiddle with the @usage syntax and I never got it to look good. Then I gave up and just accepted it would be DataFrame_dtypes. I cannot remember if I tried using <anglebrackets>. If I personally just failed to tag methods right, that is great news :)


> @sorhawell is this what you had in mind?
Yeah exactly that looks beautiful in my opinion! Does "Mkdocs" render example outputs?

Today I group methods in pkgdown by using the `@keywords DataFrame` e.g. and the divide functions into sections in the [pkgdown yaml file](https://github.com/pola-rs/r-polars/blob/e9d98de423f69a0f94c7b46504741cdc587b389c/_pkgdown.yml#L12)

I guess pkgdown was designed for smaller packages, [the current format I use on reference page](https://rpolars.github.io/reference/index.html), I think looks messy

**Comment by etiennebacher** [comment]
> Does "Mkdocs" render example outputs?

No, we'll have to find a way to do that automatically, it's actually one of the open issues on `altdoc` (I think I should update this package soon)

> I tried many times fiddle with the `@usage` syntax and I never got it to look good

If I add `#' @usage <DataFrame>$as_data_frame()` for `DataFrame_as_data_frame()` and 

```r
#' @usage
#' # S3 method
#' as.data.frame.DataFrame()
```
for `as.data.frame.DataFrame()` then I obtain this:

![image](https://user-images.githubusercontent.com/52219252/232687338-0e8e717b-bc52-41ef-a770-412edaff61c8.png)

**Comment by etiennebacher** [comment]
Closing in favor of #137
