### ISSUE TITLE
Type [i64] value expected for dynamic temporal windows

### ISSUE THREAD

**Issue by fdetsch** [pola-rs/r-polars#1141]
The sample code from #546, which used to work back then, now fails with

> Error: Execution halted with the following contexts
>    0: In R: in $with_columns()
>    0: During function call [dat$with_columns(roll_quant_int = pl$col("Temp")$rolling_quantile(0.1, 
>           window_size = 5L, min_periods = 3L, by = "Date", closed = "both"), 
>           roll_quant_time = pl$col("Temp")$rolling_quantile(0.1, window_size = "4d", 
>               min_periods = 3L, by = "Date", closed = "both"))]
>    1: The argument [window_size] caused an error
>    2: When converting into type
>    3: Expected a value of type [i64]
>    4: Got value [Rvalue: ["4d"], Rsexp: Strings, Rclass: ["character"]]
>    5: ParseIntError { kind: InvalidDigit }

The problem is probably connected to dynamic temporal windows that no longer seem to accept string language (e.g. `"4d"`, `"60m"`) as described in `?polars::Expr_rolling_quantile` and other rolling functions. 

Tested with 

```r
> utils::packageVersion("polars")
[1] '0.17.0'
```

and encountered the same error for both `datetime` and `date` columns.

**Comment by etiennebacher** [comment]
Yes this is a breaking change in 0.17.0 reported in the [changelog](https://pola-rs.github.io/r-polars/NEWS.html#polars-r-package-0170).

Basically `$rolling_quantile()` (and other `$rolling_*()` functions) used to accept a duration string in `window_size` when `by` was a date/datetime. The `by` argument has been removed and instead there is now `$rolling_quantile_by()`, meaning that `window_size` can no longer take a duration string. Based on the [py-polars docs](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.rolling_quantile_by.html#polars-expr-rolling-quantile-by) I think it's no longer possible to have `by` that is date/datetime and `window_size` that is a fixed integer.

``` r
library(polars)

## sample data
dat = transform(
  airquality,
  "Date" = as.Date(
    paste("1973", Month, Day, sep = "-")
  )
) |> 
  as_polars_df()

## set sorted flag
dat = dat$
  with_columns(
    pl$col("Date")$set_sorted()
  )

## compute rolling quantile ..
dat$
  with_columns(
    # .. with dynamic temporal window
    roll_quant_time = pl$
      col("Temp")$
      rolling_quantile_by(
        quantile = 0.1
        , window_size = "4d"
        , min_periods = 3L
        , by = "Date"
        , closed = "both"
      )
  )
#> shape: (153, 8)
#> ┌───────┬─────────┬──────┬──────┬───────┬─────┬────────────┬─────────────────┐
#> │ Ozone ┆ Solar.R ┆ Wind ┆ Temp ┆ Month ┆ Day ┆ Date       ┆ roll_quant_time │
#> │ ---   ┆ ---     ┆ ---  ┆ ---  ┆ ---   ┆ --- ┆ ---        ┆ ---             │
#> │ i32   ┆ i32     ┆ f64  ┆ i32  ┆ i32   ┆ i32 ┆ date       ┆ f64             │
#> ╞═══════╪═════════╪══════╪══════╪═══════╪═════╪════════════╪═════════════════╡
#> │ 41    ┆ 190     ┆ 7.4  ┆ 67   ┆ 5     ┆ 1   ┆ 1973-05-01 ┆ null            │
#> │ 36    ┆ 118     ┆ 8.0  ┆ 72   ┆ 5     ┆ 2   ┆ 1973-05-02 ┆ null            │
#> │ 12    ┆ 149     ┆ 12.6 ┆ 74   ┆ 5     ┆ 3   ┆ 1973-05-03 ┆ 67.0            │
#> │ 18    ┆ 313     ┆ 11.5 ┆ 62   ┆ 5     ┆ 4   ┆ 1973-05-04 ┆ 62.0            │
#> │ null  ┆ null    ┆ 14.3 ┆ 56   ┆ 5     ┆ 5   ┆ 1973-05-05 ┆ 56.0            │
#> │ …     ┆ …       ┆ …    ┆ …    ┆ …     ┆ …   ┆ …          ┆ …               │
#> │ 30    ┆ 193     ┆ 6.9  ┆ 70   ┆ 9     ┆ 26  ┆ 1973-09-26 ┆ 63.0            │
#> │ null  ┆ 145     ┆ 13.2 ┆ 77   ┆ 9     ┆ 27  ┆ 1973-09-27 ┆ 63.0            │
#> │ 14    ┆ 191     ┆ 14.3 ┆ 75   ┆ 9     ┆ 28  ┆ 1973-09-28 ┆ 63.0            │
#> │ 18    ┆ 131     ┆ 8.0  ┆ 76   ┆ 9     ┆ 29  ┆ 1973-09-29 ┆ 63.0            │
#> │ 20    ┆ 223     ┆ 11.5 ┆ 68   ┆ 9     ┆ 30  ┆ 1973-09-30 ┆ 68.0            │
#> └───────┴─────────┴──────┴──────┴───────┴─────┴────────────┴─────────────────┘
```
We'll remove the part about duration strings from the docs of `$rolling_quantile()` and friends

**Comment by fdetsch** [comment]
Understood. Of course I hadn't checked the changelog, just the help pages and [Python API reference](https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.rolling_quantile.html). Updated docs should help avoid confusion in the future &#128522;

**Comment by etiennebacher** [comment]
I'd recommend reading the changelog for every release, there are a number of breaking changes in each of them and we just don't have the manpower to follow a proper deprecation process ;)

**Comment by eitsupi** [comment]
Ideally it would be better to check if `...` is empty to detect that `by` is being used and raise an error.
Of course, in that case, the easiest way is to pull `rlang` into the dependency (#942).

**Comment by fdetsch** [comment]
Somewhat off-topic, but would have helped me avoid this: is there a mechanism to use `renv::restore()` (or `remotes::install_version()` ) with `"repos = "https://rpolars.r-universe.dev"` to install older {polars} versions? My current project was reliant on pkg version 0.13.1, but failed to find the requested source and therefore used the newest pkg version instead.

**Comment by eitsupi** [comment]
@fdetsch Please check the instllation vignette.

https://github.com/pola-rs/r-polars/blob/0735544de7635497534c9d39f394a2b16f7c9df0/vignettes/install.Rmd#L81-L90

I think I have heard that renv falls back to the source Git repository for installations from R-universe, but I have not tried it.
<https://ropensci.org/blog/2022/01/06/runiverse-renv/>

**Comment by fdetsch** [comment]
```r
remotes::install_github("pola-rs/r-polars@v0.13.1")
```

is running into version issues while trying to install the package on Amazon Linux:

> error: package `r-polars v0.36.2 (/tmp/RtmpZTx4I4/R.INSTALL1db734e9056c/polars/src/rust)` cannot be built because it requires rustc 1.73 or newer, while the currently active rustc version is 1.68.2

Not sure why it says `v0.36.2`, but according to the header it's actually trying to install `v0.13.1`.. 

There's no archived package versions on R-universe that would allow for a faster pre-built installation, correct? If not, the easiest way for me when working with {renv} would be to ship the `tar.gz` file downloaded from R-universe in `renv/local`.

**Comment by eitsupi** [comment]
@fdetsch Could you post all the installation logs? I don't think you have `NOT_CRAN="ture"` set.
And again, please check the documentation.

**Comment by etiennebacher** [comment]
> Not sure why it says v0.36.2, but according to the header it's actually trying to install v0.13.1..

The R package you want to install is version `0.13.1`. The version `0.36.2` refers to the Rust crate associated to the R package (basically we follow the numbering of rust-polars but we increment the minor number if we make a new release without bumping the rust-polars version).

The problem here is that apparently it tries to compile the source package but your Rust version is too low. You should be able to bypass that by using the binary version, which is possible by setting `Sys.setenv(NOT_CRAN = "true")` before running `remotes::install_github("pola-rs/r-polars@v0.13.1")`.

**Comment by fdetsch** [comment]
Turns out I accidentally forgot about `Sys.setenv(NOT_CRAN = "true")` when switching between sessions &#129318; thanks for the help and patience eyeryone, this should help get me going!
