### ISSUE TITLE
(re) depends on R6

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#1145]
I am told that in prehistoric times this package was built on top of R6 (e9a0fafff56bcd1ccb207617ebd451ee6d7649d8)

Is it worth going back to R6 again if there is a performance advantage to building on top of R6?
https://r6.r-lib.org/articles/Performance.html#overhead-from-using-on-objects-with-a-class-attribute

**Comment by etiennebacher** [comment]
> if there is a performance advantage to building on top of R6?

I don't really understand this. Do you know if `R6` is faster than storing functions in custom environments? I have no idea if it actually is but I don't think it really matters. In the end 99% of the time should be spent on the large data processing, having a function call that is marginally faster won't make much difference.

Also, `R6` + `roxygen2` is quite an annoying mix. Last time I used it you're forced to have all methods in the same `Rd` file, which would completely break our `mkdocs` setup.

**Comment by eitsupi** [comment]
> Also, `R6` + `roxygen2` is quite an annoying mix. Last time I used it you're forced to have all methods in the same `Rd` file, which would completely break our `mkdocs` setup.

This is simply a matter of not relying on this feature (same for arrow).

**Comment by etiennebacher** [comment]
> Do you know if R6 is faster than storing functions in custom environments? I have no idea if it actually is but I don't think it really matters

Actually storing functions in a custom env seems to be among the fastest: https://r6.r-lib.org/articles/Performance.html

**Comment by eitsupi** [comment]
> Actually storing functions in a custom env seems to be among the fastest: https://r6.r-lib.org/articles/Performance.html

Thanks for pointing that out.

I read the R6 source code to write the following, and I believe the performance is comparable, as R6 does indeed seem to generate something like this.
https://github.com/eitsupi/neo-r-polars/blob/75f740b7d29c4544188fd600f67f4a1e3403041b/R/series-series.R#L8-L27
