### ISSUE TITLE
`.to_r_vector()` -> `.as_vector()`

### ISSUE THREAD

**Issue by vincentarelbundock** [pola-rs/r-polars#117]
`.as_data_frame()` vs. `to_r_vector()` seems inconsistent. Would you consider renaming this method to `.as_vector()` or creating an alias? I'm asking because this is what I expected and it took me a few minutes to figure out what was going on.

**Comment by sorhawell** [comment]
You're right this is inconsistent.

the `to_xyz` style originates from [py-polars](https://pola-rs.github.io/polars/py-polars/html/search.html?q=to_) and rust. I think we should keep the `to_xyz` to be consistent with the other x-polars. However we could add in as aliases  `as_xyz` for any `to_xyz` method or use as via the S3-generic.


How about ?

`as_data_frame()` / `to_data_frame()`
`as_vector()` / `to_vector()`
`as_list` / `to_list`


btw also exists,  to_r() in some classes  . My idea with this was to lower mental strain while polars-scripting to just convert to the most meaningful R type.

**Comment by vincentarelbundock** [comment]
I like this. But maybe just advertise one of the as the "standard" polars approach. The to_ syntax seems perfectly fine to me as long as it's documented and used consistently in the vignettes.

A lot of the polars design choices seem to be guided by keeping the syntax close to python and rust, and I think that's a strength. My point was just that we should pick one and be consistent.

All good.

**Comment by eitsupi** [comment]
FYI, the arrow R package has `to_arrow()` and `to_duckdb()`.
https://arrow.apache.org/docs/r/reference/index.html#connections-to-other-systems
