### ISSUE TITLE
`DataFrame.sort()` and other important missing methods

### ISSUE THREAD

**Issue by vincentarelbundock** [pola-rs/r-polars#127]
`DataFrame.sort()` is not implemented yet. I think this is core functionality and a feature that would be used *very* frequently in practice. I was planning to translate it myself, but I don't currently have the time or skills, so I wanted to flag this here.

BTW, I plan to start replicating some of the [Polars User Guide](https://pola-rs.github.io/polars-book/user-guide/) examples in R. As I go along, I can assemble a TODO list of common missing functionality here if that's useful.

**Comment by sorhawell** [comment]
If have added LazyFrame.sort to #121 . I'll try to review and merge tonight.
