### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by grantmcdermott** [pola-rs/r-polars#130]
On the move so I can't fix it right now, but the [r2u section](https://github.com/pola-rs/r-polars#r2u) in the README still has the old package name. It should be:

```
rp = c("https://rpolars.r-universe.dev/bin/linux/jammy/4.2", "https://cloud.r-project.org")
install.packages(c("polars", "arrow"), repos = rp)
```

**Comment by vincentarelbundock** [comment]
Good catch. I opened a PR tof ix the typo.
