### ISSUE TITLE
Implement `mkdocs`

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#137]
See progress here: https://etiennebacher.github.io/r-polars/site

TODO list for `mkdocs` implementation:

### Questions

- [x] Do we keep a `vignettes` folder and automatically convert vignettes to markdown for the docs or do we write vignettes/articles directly in the docs? -> write vignettes as usual in the `vignettes` folder because all the docs generation should be done automatically
- [x] Code autolinking? It is not possible to autolink `polars` functions because they are not exported by `polars` (e.g `polars::DataFrame()` errors). This is also a problem on the `pkgdown` website. It is possible to autolink functions from other packages but do we actually use other packages in docs? -> let's put this aside for now because the package doesn't have deps anyway

### Formatting

- [x] Deal with strange formatting of tables (see README or Get started) happening only in mkdocs
- [x] use same color theme as the py-polars docs? -> theming can be dealt with later, it's only a few CSS variables to change
- [x] same logo?

### To fix in R docs

- [ ] Some minor formatting issues in the "Reference" pages, e.g there's the word "data" before the page title sometimes. This requires using `@docType` (see template below)
- [ ] Clean docs in R files so that they work without problems with `mkdocs` (see template below)
- [ ] Finish categorizing docs: how do we classify `Expr_` fns, or `arr_` fns?

### Other 

- [x] Evaluate examples in "Reference" pages
- [x] See if it is possible to replace usage section in md files (and not in R files so that R CMD check doesn't complain about those) -> not specific to `mkdocs` (also happens with `pkgdown`) so lower priority
- [ ] Make a yaml for CI, maybe render the "site" folder in another branch (like `pkgdown`) -> almost done but I can't push to the branch `gh-pages` because my fork (and hence the bot) doesn't have the rights (https://github.com/pola-rs/r-polars/actions/runs/4762862052/jobs/8465590223?pr=138#step:16:32)

### Outside this package

- [x] Fix `altdoc` to allow custom scripts to be ran with `altdoc::update_docs()`
- [x] Add functionality in `altdoc` to parse NEWS and link issues, PR, contributors

---

#### General class (`DataFrame`, `LazyFrame`, etc.)

Template:

```
#' Title + description
#'
#' @params
#'
#' @return 
#'
#' @rdname CATEGORY_class <----------- IMPORTANT
#'
#' @examples

foo = function()
```

Example:
```
#' Create polars DataFrame
#' 
#' Some description if needed...
#'
#' @return data.frame
#'
#' @rdname DataFrame_class <----------- IMPORTANT
#'
#' @examples
#' df = pl$DataFrame(iris[1:3,])

DataFrame = function(...) {
  ...
}
```

#### Method (`get_columns()`, etc.)

Template for method:

```
#' Title + description
#'
#' @params
#'
#' @return 
#'
#' @rdname CATEGORY_function_name <----------- IMPORTANT
#'
#' @examples

foo = function()
```

Example:

```
#' Return polars DataFrame as R data.frame
#' 
#' Some description if needed...
#'
#' @param ... any args pased to as.data.frame()
#'
#' @return data.frame
#'
#' @rdname DataFrame_as_data_frame <----------- IMPORTANT
#'
#' @examples
#' df = pl$DataFrame(iris[1:3,])
#' df$as_data_frame()

DataFrame_as_data_frame = function(...) {
  ...
}
```

#### Other rules

If the function is just a character vector then add `@docType NULL`. Example:

```r
#' Get columns (as Series)
#' ...
#' @docType NULL <------------------ IMPORTANT

DataFrame_get_columns = "use_extendr_wrapper"
```

If the general class has no specific function, it is still required to create an Rd file for it with `NULL`:
```r
#' Use groups on a Polars lazy DataFrame
#' @name LazyGroupBy_class <----------- IMPORTANT
#'
#' @return A lazy grouped DataFrame
NULL
```

**Comment by etiennebacher** [comment]
Ok so the version we have so far is quite good for me (see link at the top of the issue). There are basically two things left to do:

1. clean the R docs so that the Rd files are well named and easy to parse. See the section "To fix in R docs" above and the templates at the bottom of the first post. This will be a bit time consuming to do (especially because there are many contributions now)
2. finish automating website generation. I'm already working on this in #138 and it's unrelated to formatting and content. This will be hard to test in a PR because I don't have the right to create branches in `r-polars/polars`

@vincentarelbundock @grantmcdermott @eitsupi @sorhawell if you have remarks on formatting, content, things you'd like to see, etc. I think now is a good time

**Comment by vincentarelbundock** [comment]
@etiennebacher, this looks fantastic! Thanks for all this work.

Here are a few minor comments:

* The `DataFrame` section is unfolded by default when I open the reference page. It should be folded.
* Would be nice to use the same blue as the upstream Polars: #ecf4ff (light blue).
* Missing entries in `pl`: `DataFrame`, `Series`, `csv_reader`, `csv_reader_lazy`, `scan_parquet`, and probably others.
* How can we omit entries from the reference list? e.g., Other/Err(), Other/wrap_e_result, prepare_alpha, etc. We should make a list of internal methods and functions to make sure they are omitted.
* print.* methods should probably not be there unless they have very specific arguments.
* Why is `pl$from_arrow` displayed as `pl-cash-from_arrow`?
* `Expr` should have their own section in Reference.
* I think Get Started should be in the top navbar, along with "Articles" and "Reference". It's very important, and we can put all future articles in the Articles section.
* Links and headers are hard to read in the dark version. Should probably be a bit lighter.
* I'm not sure what the `arr_*` methods do. Should they be in their own sections?
* Weird names: Other/dot-DollarNames, etc.

Great stuff!

**Comment by sorhawell** [comment]
> Why is pl$from_arrow displayed as pl-cash-from_arrow?
I think it is the roxygen2 sanitizer fixing that $ is not allowed as @name , because .Rd filename cannot have `$` and other special characther in them.

>How can we omit entries from the reference list? e.g., Other/Err(), Other/wrap_e_result, prepare_alpha, etc. 

Previously I have tagged any internal function with @keywords internals. The tagging is likely not perfect. We can replace that way of tagging if needed.


> I'm not sure what the arr_* methods do. Should they be in their own sections?

polars have some Expr sub namespaces, arr(aka. list aka. lst), str(string), struct, meta, dt(datatime), cat(categorical), bin(binary) defined defined in expr__xxx.R. `arr` is a bit confusing because main project polars devs have not settled on one terminology. Sometimes it is an arr(rry) sometime a lst(list).

py-polars has started to sub divide methods into topic/subnamespaces . Here the subnamespace arr has its own nested tree. So does aggregation although those methods are not in subnamespace.
![image](https://user-images.githubusercontent.com/8015271/233631128-c41be105-e5c0-400a-95f4-a5a112f5e670.png)

I guess the idea with subnamespace is that e.g. any arr$ method takes a polars Series of DataType List as input. Two subnamespaces can have method of same name, but with different use case and implementation, e.g. arr$lengths (lengths of sub elements) and str$lengths (lengths of words)

**Comment by sorhawell** [comment]
It could be nice with links to source code file for each method. No idea how pkgdown does that :)

**Comment by etiennebacher** [comment]
@vincentarelbundock thanks for the comments, could use tick boxes instead of bullet points so I can check them as I progress?

**Comment by etiennebacher** [comment]
> It could be nice with links to source code file for each method. No idea how pkgdown does that :)

That should be feasible, they use the fact that the source of the function is displayed in the Rd file:

![image](https://user-images.githubusercontent.com/52219252/233639246-6ee9a037-cad8-4818-ae2b-be7b3dc44930.png)

**Comment by grantmcdermott** [comment]
Checking _very_ quickly on my phone, but this is looking good. My only high level comments are that it nice to match the theming of the main Polars page (colour/logo) and the pretty print outout of the DataFrames still needs to be fixed.

**Comment by etiennebacher** [comment]
@vincentarelbundock, it turns out I can only tick boxes on my posts, I put again your comments here, you can hide your post to save space:

- [ ] The DataFrame section is unfolded by default when I open the reference page. It should be folded.
- [ ] Would be nice to use the same blue as the upstream Polars: #ecf4ff (light blue).
- [ ] Missing entries in pl: DataFrame, Series, csv_reader, csv_reader_lazy, scan_parquet, and probably others.
- [ ] How can we omit entries from the reference list? e.g., Other/Err(), Other/wrap_e_result, prepare_alpha, etc. We should make a list of internal methods and functions to make sure they are omitted.
- [ ] print.* methods should probably not be there unless they have very specific arguments.
- [ ] Why is pl$from_arrow displayed as pl-cash-from_arrow?
- [ ] Expr should have their own section in Reference.
- [ ] I think Get Started should be in the top navbar, along with "Articles" and "Reference". It's very important, and we can put all future articles in the Articles section.
- [ ] Links and headers are hard to read in the dark version. Should probably be a bit lighter.
- [ ]  I'm not sure what the arr_* methods do. Should they be in their own sections?
- [ ] Weird names: Other/dot-DollarNames, etc

**Comment by eitsupi** [comment]
It looks very good! Thanks for all your great work.

As the number of S3 methods grows, I am wondering if these can be successfully compiled into reference pages.
(There is no reference page as they are currently marked as `@noRd`)
https://github.com/pola-rs/r-polars/blob/308cbee8001a48bef2b16dd191bcad4c237a2f71/R/s3_methods.R

**Comment by etiennebacher** [comment]
> The DataFrame section is unfolded by default when I open the reference page. It should be folded.

When we click on "Reference" it automatically expands the first section and opens the first subsection because there's no "welcome page" that summarizes all functions as in `pkgdown`. So it's not possible to fold all sections.

---

All other remarks rely on the names of the Rd files or the keywords they contain (or not). This depends on the documentation written in R files. I can't fix them all so here's a small map of how to write the R docs when you add / modify a function so that the Rd files play nicely with `mkdocs`:


![Untitled Diagram drawio](https://user-images.githubusercontent.com/52219252/233725130-f78d1cd0-ba5a-4ff1-87e6-c53abc6e735c.png)


@eitsupi for S3 methods, it's possible but it depends on how you want to organize them. Do you have in mind a subsection "S3" that will contain all S3 methods? If so, you can just refer to the map above

**Comment by eitsupi** [comment]
> @eitsupi for S3 methods, it's possible but it depends on how you want to organize them. Do you have in mind a subsection "S3" that will contain all S3 methods? If so, you can just refer to the map above

Is it possible to create another level of hierarchy in the sidebar?
In other words, I was imagining something like the following

> - DataFrame
>   - clone
>   - ...
>   - S3 methods
>     - head(\<DataFrame\>)
>     - ...

It needs to be separated from the polars methods accessed with `$`, but I think it would be easier to see if it were organized under the class.

---

Another thing I noticed is that the title of the site could be changed to something like "Polars R Package".
Like `arrow`'s site.

![image](https://user-images.githubusercontent.com/50911393/233772929-c8f8fb5a-44a9-49f1-aaee-4efd683af79a.png)

Currently, it is difficult to recognize from the navbar that this is an R package document.

![image](https://user-images.githubusercontent.com/50911393/233773196-dd7ad8e2-1a16-44e8-a6e7-c9b034b8b8cd.png)

**Comment by etiennebacher** [comment]
> Another thing I noticed is that the title of the site could be changed to something like "Polars R Package".

Agreed, I updated the page title 

> Is it possible to create another level of hierarchy in the sidebar?

Yes it is possible. Basically, what I do is:

Read Rd files 
  -> organize Rd files in sections/subsections based on the names of Rd files 
  -> make a nested list based on this hierarchy
  -> convert this nested list to the yaml format to include it in `mkdocs.yaml`

So as long as the information about S3 is somewhere in the Rd filename, it is possible to make a subsection "S3". Maybe instead of `@name DataFrame_head`, you could use `@name DataFrame_S3_head` or `@name DataFrame_head_S3`

**Comment by vincentarelbundock** [comment]
Out of curiosity, is the plan to create a separate repo for this? I think that was suggested earlier. And given the number of files, maybe it makes sense...

Or perhaps just a different branch?

**Comment by eitsupi** [comment]
Note that for now this repository does not contain the website HTML and all generated files are pushed to https://github.com/rpolars/rpolars.github.io.
https://github.com/pola-rs/r-polars/blob/2b04d3445dde103ff41099b91a7846eb4cc7f0af/.github/workflows/pkgdown.yaml#L98-L115

**Comment by eitsupi** [comment]
Is there a page to display some of the information in the DESCRIPTION file?
I think pkgdown would show it on the top page, etc.

![image](https://user-images.githubusercontent.com/50911393/233819025-5f4fb3ac-da2c-4241-9e51-a57c889b68e2.png)

**Comment by etiennebacher** [comment]
> Is there a page to display some of the information in the DESCRIPTION file?

I see only two options for this: either we put this is a navigation tab (maybe we can replace the "License" tab by an "About" tab that contains the license + citation + developer info) or we make a custom footer. Currently I see no way to add this in a sidebar like `pkgdown` does

> Out of curiosity, is the plan to create a separate repo for this? I think that was suggested earlier. And given the number of files, maybe it makes sense...

Yes either a separate repo or a separate branch, but in any case you shouldn't have to interact with the website files in PRs

**Comment by eitsupi** [comment]
> I see only two options for this: either we put this is in a navigation tab (maybe we can replace the "License" tab by an "About" tab that contains the license + citation + developer info) or we make a custom footer. Currently I see no way to add this in a sidebar like `pkgdown` does

Replacing the License page seems a good idea!
