### ISSUE TITLE
`pl$count()`, `pl$mean()` and other context expressions

### ISSUE THREAD

**Issue by vincentarelbundock** [pola-rs/r-polars#144]
`pl$count()` does not appear to be implemented.

I am translating all the examples in [the Python Polars User Guide](https://pola-rs.github.io/polars-book/user-guide/) to R, and a lot of their examples use this kind of construction:

```r
pl$DataFrame(mtcars)$groupby("cyl")$agg(pl$count())
```

**Comment by sorhawell** [comment]
oups [accidentially pushed directly to main](https://github.com/pola-rs/r-polars/commit/fe763076fe0c69d662d773a974cd9bc37bce4b4b)

aboce commit should adds pl$count, first , last

**Comment by vincentarelbundock** [comment]
Thanks, will do this when I find some time.

**Comment by eitsupi** [comment]
> oups [accidentially pushed directly to main](https://github.com/pola-rs/r-polars/commit/fe763076fe0c69d662d773a974cd9bc37bce4b4b)

It may be worth protecting the branch.
If you protect branches and enforce testing on PRs, you also have the advantage of being able to enable auto-merge.

**Comment by vincentarelbundock** [comment]
Duplicate of https://github.com/pola-rs/r-polars/issues/144

**Comment by sorhawell** [comment]
```r
> pl$DataFrame(mtcars)$groupby("cyl")$agg(pl$count())
shape: (3, 2)
┌─────┬───────┐
│ cyl ┆ count │
│ --- ┆ ---   │
│ f64 ┆ u32   │
╞═════╪═══════╡
│ 6.0 ┆ 7     │
│ 4.0 ┆ 11    │
│ 8.0 ┆ 14    │
└─────┴───────┘
```
