### ISSUE TITLE
long_arms64 branch?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#145]
The README says the following, is this still correct today?

The `long_arms64` branch has not been updated for a long time. (last commit was 2 months ago 15501904b49aaa52eadfe349fc42df08af206e4d)

````md
One exception worth noting is MacOS (arm64), i.e. systems based on the
new M1/M2 “Silicon” chips. To install **polars** on one of these
machines, we need to build the package from source and this requires
[Xcode](https://developer.apple.com/xcode/) (`xcode-select --install`).
Once Xcode is installed, you can run the below code chunk to build
**polars**. The corresponding `Makevars` script will download a \~200MB
cross-compiled object file, while your machine links and builds the
final R package.

``` r
# install.packages("remotes")

remotes::install_github(
  "https://github.com/pola-rs/r-polars",
  ref = "long_arms64", force =TRUE
)
```
````

**Comment by sorhawell** [comment]
I struggled to write an automated workflow for this, and released some builds manually. But it took too much time, so I would to either drop it for now.

Ideally the install snippet should reference that specific commit, which in turn lookup the correct object files for that commit to assemble the final R package. We cannot assemble the final R package without arm64 machines.
