### ISSUE TITLE
Some methods execute `LazyFrame$collect()`

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#146]
https://github.com/pola-rs/r-polars/blob/4806147b638f06145276d5384768ca5fd178186d/R/s3_methods.R#L23
I think this is very dangerous because collect might perform a large number of calculations.

See `arrow::Dataset`. `arrow::Dataset` does not have methods which needs collect.
https://github.com/apache/arrow/blob/0bf777a5952be012e41f5b1ad443d4fec38e6f5a/r/R/dataset.R

...Or, `tbl_lazy` returns NA for the number of rows that cannot be determined until collect is executed.
https://github.com/tidyverse/dbplyr/blob/505ca7004ce339f14cfc54aa714c5492d5bc2042/R/tbl-lazy.R#L41-L43

**Comment by vincentarelbundock** [comment]
That's a very good point. I can re-write those methods to tell users that they must ˋcollect()` before calling ˋdim()` and friends.

**Comment by sorhawell** [comment]
I agree. I like in polars that only collect triggers collect. In spark it is less obvious I think.

**Comment by vincentarelbundock** [comment]
Can be closed.
