### ISSUE TITLE
`LazyFrame.columns` attribute

### ISSUE THREAD

**Issue by vincentarelbundock** [pola-rs/r-polars#150]
Opening this issue because I don't want this feature request to be lost. Once we have `LazyFrame.columns`, we should be able to have `[.LazyFrame` easily by uncommenting some of the code in `extendr-wrappers.R` and `test-s3-methods.R`.

**Comment by sorhawell** [comment]
I wonder if LazyFrame for any operation supports static analysis (no collect needed) of schema/columns. It looks like it.

**Comment by sorhawell** [comment]
given #135 we should probably make sure every S3-generic method is very cheap to run. In worst case we have to sacrifice that the interface of LazyFrame resembles a data.frame.

**Comment by eitsupi** [comment]
Closed by #250

**Comment by eitsupi** [comment]
@vincentarelbundock Could you take a look at this?

https://github.com/pola-rs/r-polars/blob/641e11541e1c2afb6944108de486758c8c01baa3/R/s3_methods.R#L71-L74

**Comment by vincentarelbundock** [comment]
See https://github.com/pola-rs/r-polars/pull/301
