### ISSUE TITLE
`[[.DataFrame` does not seem working

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#158]
``` r
polars::pl$DataFrame(mtcars)[["am"]]
#> Error in environment(func) <- environment(): attempt to set an attribute on NULL
```

<sup>Created on 2023-04-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Am I misunderstanding something?

**Comment by sorhawell** [comment]
@eitsupi [[ and $ are taken by extendr for method chaining. See extendr-wrappers.R

Maybe at some point extendr could do with just $, but likely not now.

**Comment by eitsupi** [comment]
Oh, I misunderstood the use of this!
Thanks for pointing that out.

**Comment by vincentarelbundock** [comment]
Example: I've used `[[]]` in `patrick` examples to select methods programmatically.

**Comment by sorhawell** [comment]
good reason to keep [[ for methods

**Comment by etiennebacher** [comment]
For anyone seeing this later, you can extract a vector like this:
``` r
polars::pl$DataFrame(mtcars)$get_column("am")$to_r()
#>  [1] 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1
```

Closing since the behavior of `[[` will likely not change.
