### ISSUE TITLE
Set up Makefile or something to run tasks

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#173]
Other repositories in this organization seem to use Makefiles to define tasks.

By the way, I prefer Task rather than Make (like https://github.com/eitsupi/prqlr/blob/b6b822765dcddb47a92de0f047a0b6e071a7fc5d/Taskfile.yml), which I think is easier to use than Make in terms of built-in documentation and Windows support with built-in sh.
https://taskfile.dev/

**Comment by vincentarelbundock** [comment]
I think that's a great idea.

Task looks cool, thanks for the link!

That said Makefiles work basically everywhere, and almost everyone know how to use them. There is value in standardization and in not forcing new devs to install and learn new tech.

**Comment by sorhawell** [comment]
Interesting, that could potentially be very useful. Looking forward to try it

**Comment by etiennebacher** [comment]
(Follow-up on [this comment](https://github.com/pola-rs/r-polars/pull/138#discussion_r1175154054)) The R code for generating docs should be:

```r
pak::pak(c("etiennebacher/altdoc", "yaml", "magrittr", "cli", "tinkr", "stringr", "Genentech/rd2markdown@c4fb386"))
altdoc::update_docs(custom_reference = "docs/make-docs.R")
```
(assuming `pak` is installed)

**Comment by eitsupi** [comment]
> (Follow-up on [this comment](https://github.com/pola-rs/r-polars/pull/138#discussion_r1175154054)) The R code for generating docs should be:
> 
> ```r
> pak::pak(c("etiennebacher/altdoc", "yaml", "magrittr", "cli", "tinkr", "stringr", "Genentech/rd2markdown@c4fb386"))
> altdoc::update_docs(custom_reference = "docs/make-docs.R")
> ```
> 
> (assuming `pak` is installed)

Since I have updated the DESCRIPTION file in #138, `pak::local_install_deps(dependencies = c("all", "Config/Needs/website"))` should install all dependencies.
