### ISSUE TITLE
Making r-polars a community project

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#174]
Dear all @eitsupi @grantmcdermott  @vincentarelbundock  @etiennebacher  did I forget any?

I'm so proud and happy to see this project fastly outgrowing me as a single person.
I have a paternity leave and some freelance contracts until mid summer and can only contribute 1-2 hours in the evening. I can't sufficiently keep up with every awesome PR and I should not  hold back progress.

In general, I think contributions have been great and I learn a lot.

### Suggestions to PR bottleneck:
 - How about we make a bigger group of admins, like 3-5 or so?
 - All PR's need at least one reviewer, and one admin to push the button.
 - A reviewer need not to be an admin, but must be a regular contributor.

### Suggestions on authorship and final say.
 - Admins will act on behalf of the project and the expected intention of other admins.
 - Admins will start open discussions and seek consensus.
 - Admins although passionate , will try to avoid bike-shedding and will applaud any incremental positive development.
 - Admins agree on authorship and maintainer-role.
 - Finally r-polars is a part of the pola-rs organization and admins can be overruled/replaced by the pola-rs organization.

### misc
pola-rs org has a [code of conduct](https://github.com/pola-rs/.github/blob/3de0f36fd9abda2368679937da56c685c9cfbd59/CODE_OF_CONDUCT.md) we must adhere to. I personally think it is a good code of conduct.

**Comment by etiennebacher** [comment]
This looks great, I'd be happy to be part of this group of admins. As @vincentarelbundock said in another comment somewhere, you've already been very fast in reviewing PRs and answering questions so thanks a lot for this and for developing this project mostly on your own so far.

I agree with all suggestions above. Maybe the `main` branch should be locked so that the only way to update it is through a PR? (I can't see if this is already the case)

**Comment by vincentarelbundock** [comment]
All of this sounds very good and reasonable. I like that you want to follow the upstream project closely, and the code of conduct seems excellent.

I don't yet feel I have a good grasp on the full code base, but I look forward to learning more Rust and `polars`. My availabilities are somewhat variable, so I can't make hard promises on a number of hours. That said, I often do have some free "open source time," and am happy to help in any capacity you find useful, subject to life events, etc.

**Comment by grantmcdermott** [comment]
+1 to all of the above. I'm pretty time constrained at the moment, but happy to contribute where and when I can. (Using some core guiding principles and guardrails, from CoC to protecting the main branch from direct commits, makes a ton of sense to me.)

**Comment by sorhawell** [comment]
awesome @grantmcdermott, @eitsupi , @etiennebacher @vincentarelbundock  you're now co-admins :)
In future we should probably only upgrade additional contributors as maintainers.

These are the current branch protection rules
<img width="932" alt="image" src="https://user-images.githubusercontent.com/8015271/234391077-3038f51f-ab15-4e01-b60d-ba144dbf9647.png">

**Comment by eitsupi** [comment]
Related to this, I have changed the merge commit message to just the PR title, like other pola-rs repositories.
If anyone disagrees, please let me know.

![image](https://user-images.githubusercontent.com/50911393/234556014-0c833819-8e6f-4e32-be7a-5ac9e8c8c418.png)
