### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#182]
Sorry for yet another (but hopefully final) todo list for docs. I prefer this rather than listing issues / suggestions in PR comments. @sorhawell @grantmcdermott @vincentarelbundock @eitsupi please edit this post or add comments if you find some issues while browsing the docs or have some suggestions on how to improve them.

- [x] Make a reference landing page 
- [x] Fix section order in reference pages (e.g the description comes after the "Returns" section), reported in https://github.com/Genentech/rd2markdown/issues/30
- [x] Split `Expr` docs into several subsections as in [py-polars](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/aggregation.html)
- [x] Footnote hyperlinks are not displaying properly. (Search for "[^1]" in the [vignette](https://rpolars.github.io/articles/polars/).)
- [ ] Table formatting works in some setups but not all (e.g mobile + laptop on Ubuntu)
- [x] suffix all roxygen2 r-polars classes `#' @name` with `_class` to let docs auto discover the classes
- [x] make a tab "About" that contains license + citation + developer info
- [x] Replace `DataFrame_clone()` by `<DataFrame>$clone()` in "Usage" section (and same for all other functions)
- [ ] Use [`@inherit`](https://roxygen2.r-lib.org/reference/tags-reuse.html) and friends to automatically use the same docs for LazyFrame and DataFrame
- [x] Add `@doctype NULL` and `@format NULL` everywhere the function is just a character `"use_extendr_wrapper"`. This is to avoid the useless "Format" section (like [here](https://rpolars.github.io/reference/Expr_product/)) that is usually for data.

**Comment by vincentarelbundock** [comment]
Thanks for all your work on this Etienne! FYI, when PR #175 is merged, I intend to take a close look at all the documentation. I'll try to address some of the issues listed here.

**Comment by grantmcdermott** [comment]
Added a minor point about footnotes. But in general just want to say that the docs are looking fantastic. Thanks Etienne!

**Comment by sorhawell** [comment]
added _class tagging of all roxygen2 docs of polars classes. I'll happily do that :)
It looks like I have 1-3 weeks nearly full time polars starting next week.

**Comment by vincentarelbundock** [comment]
> added _class tagging of all roxygen2 docs of polars classes. I'll happily do that :) It looks like I have 1-3 weeks nearly full time polars starting next week.

@sorhawell If you give me a bit of time, I'll attempt this and some of the other items on the list.

**Comment by etiennebacher** [comment]
For table formatting issues, take a look at the CSS rules in https://github.com/pola-rs/polars-book/pull/302 (they switched the book to mkdocs material last week, perfect timing!)

**Comment by etiennebacher** [comment]
There are a lot of functions that exist both for DataFrame and LazyFrame. We should use [`@inherit`](https://roxygen2.r-lib.org/reference/tags-reuse.html) and friends to automatically use the same docs for the two.

Example: `filter()` has different documentation for [LazyFrame](https://rpolars.github.io/reference/LazyFrame_filter/) and [DataFrame](https://rpolars.github.io/reference/DataFrame_filter/) while it should be the same

Same thing for `GroupBy` and `LazyGroupBy`

**Comment by eitsupi** [comment]
@etiennebacher Can we close this?

**Comment by etiennebacher** [comment]
I think so, I'll improve the Expr docs later
