### ISSUE TITLE
Make print snapshots more robust

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#191]
I think the polars print is affected by the terminal size (?).
This could affect README.md regenerations and snapshot tests, so it may be worth enforcing that the print results are the same in all environments.

**Comment by etiennebacher** [comment]
Snapshots should all have the same width since we're using `testthat` 3rd edition (cf https://github.com/r-lib/testthat/issues/1567). Are there some examples where the snapshots width changes?

**Comment by eitsupi** [comment]
Thanks for pointing that, it seems good!

I don't know the detailed reason, but the snapshot change occurred in this PR as commented below.
https://github.com/pola-rs/r-polars/pull/125#issuecomment-1513853936

**Comment by etiennebacher** [comment]
Is this still an issue?

**Comment by eitsupi** [comment]
If it reoccurs, I will reopen.
