### ISSUE TITLE
R-universe r-polars build fails because rust-polars is no longer backwards compatible with rustc 1.65.0 stable

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#208]
R-universe build fails
https://github.com/r-universe/rpolars/actions/runs/4884403053

~~I tried to downgrade to rust 1.65 stable locally, but I got no errors so far.~~
~~Something with simd is mentioned in some of the compiler errrors, but not sure what it is about.~~

EDIT: In a clean build I was able to reproduce the error by downgrading to rustc 1.65 stable

**Comment by sorhawell** [comment]
the issue is upstream rust-polars has [adopted crate argminmax 0.6.1](https://github.com/pola-rs/polars/pull/8074) which shows to no bet backwards compatible with rustc 1.65.0 stable but onlye 1.66 stable. The minimal previous minimal rustc version was 1.62 for polars.

argminmax 0.6.1 currently needs rustc >= 1.66.0 to no  give the [following compiler error](https://github.com/r-universe/rpolars/actions/runs/4938598307/jobs/8828571811)


possible solutions:
 - ask R universe to upgrade to rustc 1.66.0  (problematic because a CRAN release would then be several more years away)
 - kindly ask polars to feature gate argminmax crate
 - kindly ask argminmax to become backwards compatible with 1.65 stable
 - for rust-polars where argminmax was never adopted (could work in the short run, would probably to too difficult to maintain over time)

**Comment by sorhawell** [comment]
[error reproduced in hello_r_universe](https://github.com/pola-rs/r-polars/actions/runs/4941854934/jobs/8835133766)

**Comment by eitsupi** [comment]
Thanks for taking a look at this.

Perhaps Debian testing will skip Rust 1.64 and 1.65, so this problem will be solved when we can build this package in CRAN machine anyway.
https://tracker.debian.org/pkg/rustc

> we ourselves should probably add an "R-universe-like" build to our regular PR checks to discover such backwards compatibility issues earlier.

I too thought that the handling of SIMD disabled should be tested more.

If someone wants to work on it, one way is to rewrite Cargo.toml by detecting the available Rust state by the `configure` script like the `gifski` package, I think.
https://github.com/r-rust/gifski/blob/68911d927fb34c43dede24ce1baab73346e8bf04/configure#L11-L22

**Comment by sorhawell** [comment]
> Perhaps Debian testing will skip Rust 1.64 and 1.65, so this problem will be solved when we can build this package in CRAN machine anyway.

R-universe build can run on 1.65.0 when setting `opp-level=1` specifically for argminmax. Probably we should cross our fingers for Debian skipping 1.65, and otherwise we can mitigate issue.

**Comment by sorhawell** [comment]
seems to work alright now

**Comment by eitsupi** [comment]
Related to #279

**Comment by eitsupi** [comment]
Debian testing migration to Rust 1.66 is in progress.
This means that if we want to do a CRAN release, MSRV is sufficient for Rust 1.66.

However, Ubuntu is currently Rust 1.65, so if we consider binary installation with the Posit Package Manager, we will need to resolve this issue and support Rust 1.65.
