### ISSUE TITLE
Flaky builds due to network errors

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#211]
These days I personally find that quite often some network error prevents installation of an R package or a rust crate, so I manually have to rerun failed builds.

Maybe this action can solve flaky network connection
https://github.com/smorimoto/tune-github-hosted-runner-network

**Comment by etiennebacher** [comment]
Looks like it's still failing: https://github.com/pola-rs/r-polars/actions/runs/4958169175/jobs/8870810591

**Comment by etiennebacher** [comment]
This seems corrected now, do you still want to add the action you linked?

**Comment by sorhawell** [comment]
yeah I have not have a fail for long time. I will close it.

For the record. The tuning github action did not seem to immediately fix anything.
