### ISSUE TITLE
rust polars doesn't support the latest Rust nightly toolchain

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#216]
Build currently fails due to compatibility with 2023-05-13 nightly toolchain.
https://github.com/pola-rs/r-polars/blob/6a3522d11ddbbba9dc739918e9ee4d1ca2c10bcf/src/rust/rust-toolchain#L2
https://github.com/pola-rs/r-polars/blob/6a3522d11ddbbba9dc739918e9ee4d1ca2c10bcf/Makefile#L34-L36

Definitely need to specify a date like this.
https://github.com/pola-rs/polars/blob/64dabba165a811179197687f193037daba1103c1/rust-toolchain.toml#L2

Unfortunately, there does not seem to be a command to install the toolchain by referencing a rust-toolchain file at this time (rust-lang/rustup#2686), so it appears that the date needs to be entered in the two places above.

**Comment by sorhawell** [comment]
I think this makes a lot of sense. I had missed upstream polars was pinning the nightly version. I guess we should just bump rustc and rust-polars simultanously in the future.

**Comment by sorhawell** [comment]
this could potentially improve rust compilation caching

**Comment by sorhawell** [comment]
oups I forgot about release and docs also needs to have nightly pinned
