### ISSUE TITLE
rename subnamespace `Expr.arr` to `.list`

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#230]
https://github.com/pola-rs/polars/pull/8999

**Comment by etiennebacher** [comment]
This has to be done at some point but it would bloat the code to keep both `arr` and `list` namespaces. I suppose we can replace all `arr` by `list` at once, which will be a massive breaking change. That could be worth a new release (maybe `0.8.1`?). 

What do you think @sorhawell @eitsupi ?

**Comment by sorhawell** [comment]
The subnamespaces can be moved around relatively easy. I can start a  community PR with the namespace rerouting

Maybe the complete change could be done in two PRs

Patch update to 0.8.1 or so
 -  reroute arr subnamespace from Expr$arr to also Expr$list (~5 lines of r code)
 -  update docs to recommend list over arr + deprecation warning on arr (many search replace, but hopefully fast)
 
Minor update to 0.9 maybe
 - close Expr$arr access
 -  rename internally to remove mentions of arr

**Comment by etiennebacher** [comment]
Sounds good to me. I think we could release 0.8.1 right after your "rerouting" PR and then take more time until 0.9.0 so that the deprecation notice is visible to the users at least for a few weeks

**Comment by etiennebacher** [comment]
`arr` is now deprecated and will be removed in 0.9.0
