### ISSUE TITLE
Melt and Pivot

### ISSUE THREAD

**Issue by adenoz** [pola-rs/r-polars#231]
I'm new to the `r-polars` library but thought to offer this issue.

In attempting to migrate from `tidyr` and `dplyr`, I noticed that the [melt](https://pola-rs.github.io/polars-book/user-guide/transformations/melt/) and [pivot](https://pola-rs.github.io/polars-book/user-guide/transformations/pivot/) functions don't seem to be implemented in the R version yet? This may be a user issue but I have tried a number of ways in case it was simply not documented.

I personally think these two functions are really important for data wrangling so just highlighting some interest via this issue.

P.S. Really loving `polars` in general as it will make moving between R, Python and Rust more seamless.

**Comment by sorhawell** [comment]
It is true we have basically all Expr methods translated but not all Frame methods. I will try to translate these two tonight.

**Comment by adenoz** [comment]
Oh wow. That's frankly quite awesome.

**Comment by sorhawell** [comment]
[currently upstream polars does not have a lazy pivot](https://github.com/pola-rs/polars/issues/8903)

**Comment by sorhawell** [comment]
I got started tonight with melt
