### ISSUE TITLE
Add `with_column_name` argument in lazy_csv_reader() method

### ISSUE THREAD

**Issue by ddotta** [pola-rs/r-polars#256]
Question:

Is [lazy_csv_reader](https://rpolars.github.io/reference/lazy_csv_reader/) in R the equivalent of [scan_csv](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_csv.html#polars-scan-csv) in Python?

If so, it would be great to be able to add the `with_column_names` argument, which is very useful to modify the header before scanning. 👍 

Many thanks!

**Comment by sorhawell** [comment]
> Is [lazy_csv_reader](https://rpolars.github.io/reference/lazy_csv_reader/) in R the equivalent of [scan_csv](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.scan_csv.html#polars-scan-csv) in Python?

yes and we should rename to match python

> it would be great to be able to add the with_column_names argument
will look into that likely on Monday :)

**Comment by ddotta** [comment]
Thanks!
