### ISSUE TITLE
Implement native method to export polars DataFrames to Excel

### ISSUE THREAD

**Issue by ddotta** [pola-rs/r-polars#257]
In [the cookbook](https://ddotta.github.io/cookbook-rpolars/import_export.html#export-data) I wrote this:

> Unlike Python, the Polars R API does not yet contain native methods for **exporting to Excel format**.
The best current solution is to use the [data.frame conversion method](#from-seriesdataframes-to-vectordata.frames) and then use the [{openxlsx}](https://ycphs.github.io/openxlsx/index.html) package or one of its [{tablexlsx}](https://ddotta.github.io/tablexlsx/) wrapper to export these DataFrames in xlsx format.  
Fortunately, the contributors to the R {polars} package are in full development and we hope soon to have methods for exporting to arrow or tibbles, for example! 💪

**Comment by sorhawell** [comment]
I took a look at py-polars impl it seems rely on python package XlsxWriter and not some dedicated polars/rust writer.

@ddotta  what do you see as the benefits of writing directly to xlsx and not via data.frame?
I guess xlsx-writers are rather slow so the data.frame will no be terrible.

**Comment by ddotta** [comment]
Yes, that's what I've seen too (the XlsxWriter dependency).
I agree with you that it can't be much more efficient than converting to a data.frame and then using {openxlsx}.
The only thing compared to a native method is that there's an extra conversion step...

I'll change the export text to include this.
I think you can close the issue 👍 
Thanks!

**Comment by eitsupi** [comment]
FYI, there is also `openxlsx2`
https://github.com/JanMarvin/openxlsx2

**Comment by ddotta** [comment]
Thanks @eitsupi I'll keep a note of it

**Comment by eitsupi** [comment]
Ok, I am closing this because the existing solutions seem sufficient.
