### ISSUE TITLE
DataFrame$select  and LazyFrame$select should accept list-args

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#259]
this should be possible
```R
l_expr = list(
pl$col("a"),
pl$col("b")
)

pl$DataFrame(a = 1:3, b=1:3)$select(l_expr)
```
today one have to use do.call

```R
pl$DataFrame(a = 1:3, b=1:3)$select |> do.call(l_expr)
```

bonus points for deprecating `construct_ProtoExprArray` and just use on rust side `robj_to!(Vec,Expr)`

**Comment by etiennebacher** [comment]
I think this can be closed (unless you want to keep it open for deprecating `construct_ProtoExprArray `)
