### ISSUE TITLE
implement `<LazyFrame>.profile()`

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#261]
nice to have, also for tutorials on polars.
[https://pola-rs.github.io/polars/py-polars/html/reference/lazyframe/api/polars.LazyFrame.profile.html#polars.LazyFrame.profile](https://pola-rs.github.io/polars/py-polars/html/reference/lazyframe/api/polars.LazyFrame.profile.html#polars.LazyFrame.profile)

**Comment by Sicheng-Pan** [comment]
Completed with #323
