### ISSUE TITLE
Workflows without the `simd` feature

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#263]
After #262 is merged, R CMD check, MSRV check, etc. should be done without the `simd` feature.

**Comment by etiennebacher** [comment]
Looks like #262 enabled `simd` in all workflows. Isn't in contradiction with what you want to do here?

**Comment by eitsupi** [comment]
Sorry for the confusion, #262 was simply intended to be a feature split, so the intent was to defer disabling simd on the workflow.
