### ISSUE TITLE
Can't build with Rust stable toolchain

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#276]
The changes made by #233 prevent builds except for nightly-toolchain.
https://github.com/pola-rs/r-polars/actions/runs/5411224946/jobs/9833719506?pr=274

Can we revert this change for now? Or Could you fix that error?

_Originally posted by @eitsupi in https://github.com/pola-rs/r-polars/issues/80#issuecomment-1612903299_

**Comment by sorhawell** [comment]
@Sicheng-Pan @eitsupi 
Sorry that is a blunder from my side, I overlooked PR used an unstable feature.

I think there is tag to forbid the compiler to use unstable features.

I will make a dumb hotfix for now.

@Sicheng-Pan  maybe you can find another way to bubble the various errors.

**Comment by Sicheng-Pan** [comment]
@sorhawell Yeah I should have avoided using nightly features. I checked your PR and it looks good to me.

**Comment by eitsupi** [comment]
Thanks for taking a look at this right away!
I think it is definitely necessary to test the build on CI with the stable toolchains. (#274)
