### ISSUE TITLE
replace use of `pl$polars_set_options()` with `pl$options$...` in docs

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#316]
`pl$options` supports auto completion and make it easier to discover options

<img width="355" alt="image" src="https://github.com/pola-rs/r-polars/assets/8015271/f0aeec69-a79b-4c59-b5b0-80a90a6c6397">

**Comment by Surya-Narayan** [comment]
Hello, I would like to work on this issue if its okay. I did try to find 'pl$polars_set_options()' in the docs directory but was not able to. Can you help me with what exactly is the requirement ?

**Comment by sorhawell** [comment]
Dear @Surya-Narayan  . That sounds amazing :)

[here are the current docs:](https://rpolars.github.io/reference/polars_options/) 

current use set/get_polars_options
https://github.com/search?q=repo%3Apola-rs%2Fr-polars%20set_polars_options&type=code
https://github.com/search?q=repo%3Apola-rs%2Fr-polars%20get_polars_options&type=code

replace `pl$set_polars_options(no_messages=TRUE)` with `pl$options$no_messages(TRUE)`
and likewise use `pl$options$no_messages()` instead of get.

You should fork r-polars main. Then make a new branch called e.g. options_docs and work there. You can fairly fast make a draft PR back to r-polars to see if tests are passing, and we will take it from there.

**Comment by Surya-Narayan** [comment]
Okay got it. You can assign this to me! I am changing the set_polars_options in examples and I found these oddities : 

<img width="1017" alt="image" src="https://github.com/pola-rs/r-polars/assets/35400234/cf136a74-5df9-49d1-bdc8-16259a758460">

How do I approach these ?

**Comment by etiennebacher** [comment]
@sorhawell I'm not entirely convinced by this change, it would feel a bit weird to do:
```r
pl$options$strictly_immutable(TRUE)
pl$options$debug_polars(TRUE)
```
I think it's good to have `pl$options` to get a named list of options that is easy to use (which is currently the case), and `pl$set_options()` to set options like this:
```r
pl$set_options(strictly_immutable = TRUE, debug_polars = TRUE)
```
This still needs some renaming from `set_polars_options()` to `set_options()` (the `pl$` prefix already indicates that this is for `polars` only). @Surya-Narayan are you still interested in making this renaming?

Btw, I think we could add a `global_string_cache` item in `pl$options`.

**Comment by etiennebacher** [comment]
> If going along with your suggestion. Maybe every option arg in pl$set_options() could be named and defaulted to NULL, where NULL is aliased with no change. We can model unset as NA or "".

Yes we should use named arguments and auto-completion would work. I just made a quick example with `strictly_immutable`:

![image](https://github.com/pola-rs/r-polars/assets/52219252/45c3968e-c0bb-4ce3-8ea2-2540f356f974)

Would you be ok with something like this? I don't see why we should set them to `NULL` though, why not put `TRUE` or `FALSE` as default value for each argument? 

> We could make get_set_global_rpool_cap private and read/write the state via pl$options$rpool_cap pl$set_options(rpool_cap = 42) such that it in any ways appears to be an R side state.

This would make sense to me, I think it's confusing to set some options with `pl$set_polars_options()` and others with `pl$set_global_rpool_cap()`. 

> Instead we could have some "verb"-options like pl$enable_string_cache() and pl$reset_string_cache() which are functions and still nudge user towards using pl$with_string_cache()

There's a PR in rust-polars to fix the strange way to set string cache: https://github.com/pola-rs/polars/pull/11020

**Comment by sorhawell** [comment]
> Would you be ok with something like this? I don't see why we should set them to NULL though, why not put TRUE or FALSE as default value for each argument?

it would force updating state of all options that are not `NULL`  depending on underlying state representations in R and rust, maybe that is less elegant. But probably OK.

However something like this would surprise a user, as `strictly_immutable` is reverted to its default (TRUE) by chaining another option.
```R
pl$set_options(strict_immutable = FALSE)
pl$set_options(some_other_option = FALSE)

pl$options$strict_immutable
> TRUE
```

**Comment by etiennebacher** [comment]
This is mostly outdated now, I'll open another issue about what to do with `global_rpool_cap()`
