### ISSUE TITLE
Implement methods to check if an object is a Series or a DataFrame ?

### ISSUE THREAD

**Issue by ddotta** [pola-rs/r-polars#337]
I don't know if this exists but it would be nice to have one or more methods that allow to check (with a Boolean) if an object is a `Series` or a `DataFrame`.  

For the moment the only thing we can do is to display the object in the console to check this.

Maybe something like this ?

```r
is_dataframe(pl$DataFrame(iris)[,"Petal.Length"]) # FALSE
is_dataframe(pl$DataFrame(iris)[,c("Petal.Length","Petal.Width")]) # TRUE
is_series(pl$DataFrame(iris)[,"Petal.Length"]) # TRUE
is_series(pl$DataFrame(iris)[,c("Petal.Length","Petal.Width")]) # FALSE
```
I don't think it exists in `py-polars`...

**Comment by vincentarelbundock** [comment]
Out of curiosity, what would be the benefit of a dedicated method? The downside is that it clutters the package, but I’m not sure what the upside would be relative to this, which seems both simple and “symmetric” across implementations:

R:

``` r
library(polars)
d = pl$DataFrame(a = 1:10)
inherits(d, "DataFrame")
# [1] TRUE
```

Python:

``` python
import polars as pl
d = pl.DataFrame({"a": list(range(1, 11))})
isinstance(d, pl.DataFrame)
# True
```

**Comment by ddotta** [comment]
@vincentarelbundock It was for unit tests but I hadn't thought of using `inherits()`.  
Thank you ! I'll close the issue
