### ISSUE TITLE
Manually converting `LazyGroupBy` to `LazyFrame` breaks printing

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#338]
I tried to manually convert a `LazyGroupBy` object to a `LazyFrame` using `class()` but it generates an error when I want to print the output. Is this expected?
``` r
library(polars)
#> Warning: le package 'polars' a été compilé avec la version R 4.3.1

test1 <- pl$LazyFrame(mtcars)
test1
#> [1] "polars LazyFrame naive plan: (run ldf$describe_optimized_plan() to see the optimized plan)"
#> DF ["mpg", "cyl", "disp", "hp"]; PROJECT */11 COLUMNS; SELECTION: "None"

test2 <- test1$groupby("am")
test2
#> polars LazyGroupBy: 
#> LazyGroupBy (internals are opaque)

class(test2) <- "LazyFrame"
test2
#> [1] "polars LazyFrame naive plan: (run ldf$describe_optimized_plan() to see the optimized plan)"
#> Error in .pr$LazyFrame$print(x): expected LazyFrame
```

---

To give some context, in `tidypolars` if the user has a `group_by()` then the data is either `GroupBy` or `LazyGroupBy`. This is fine to use `summarize()` (which uses `$agg()` under the hood) but to be able to use `mutate()` on grouped data I need to convert `GroupBy` to `DataFrame` and `LazyGroupBy` to `LazyFrame`. This is where I got the error. If you have a better way to ungroup data, I'm all for it

**Comment by etiennebacher** [comment]
Note however that there's no problem with `DataFrame`:
``` r
library(polars)

test1 <- pl$DataFrame(mtcars)
test1
#> shape: (32, 11)
#> ┌──────┬─────┬───────┬───────┬───┬─────┬─────┬──────┬──────┐
#> │ mpg  ┆ cyl ┆ disp  ┆ hp    ┆ … ┆ vs  ┆ am  ┆ gear ┆ carb │
#> │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ --- ┆ --- ┆ ---  ┆ ---  │
#> │ f64  ┆ f64 ┆ f64   ┆ f64   ┆   ┆ f64 ┆ f64 ┆ f64  ┆ f64  │
#> ╞══════╪═════╪═══════╪═══════╪═══╪═════╪═════╪══════╪══════╡
#> │ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
#> │ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
#> │ 22.8 ┆ 4.0 ┆ 108.0 ┆ 93.0  ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 1.0  │
#> │ 21.4 ┆ 6.0 ┆ 258.0 ┆ 110.0 ┆ … ┆ 1.0 ┆ 0.0 ┆ 3.0  ┆ 1.0  │
#> │ …    ┆ …   ┆ …     ┆ …     ┆ … ┆ …   ┆ …   ┆ …    ┆ …    │
#> │ 15.8 ┆ 8.0 ┆ 351.0 ┆ 264.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 4.0  │
#> │ 19.7 ┆ 6.0 ┆ 145.0 ┆ 175.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 6.0  │
#> │ 15.0 ┆ 8.0 ┆ 301.0 ┆ 335.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 8.0  │
#> │ 21.4 ┆ 4.0 ┆ 121.0 ┆ 109.0 ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 2.0  │
#> └──────┴─────┴───────┴───────┴───┴─────┴─────┴──────┴──────┘

test2 <- test1$groupby("am")
test2
#> shape: (32, 11)
#> ┌──────┬─────┬───────┬───────┬───┬─────┬─────┬──────┬──────┐
#> │ mpg  ┆ cyl ┆ disp  ┆ hp    ┆ … ┆ vs  ┆ am  ┆ gear ┆ carb │
#> │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ --- ┆ --- ┆ ---  ┆ ---  │
#> │ f64  ┆ f64 ┆ f64   ┆ f64   ┆   ┆ f64 ┆ f64 ┆ f64  ┆ f64  │
#> ╞══════╪═════╪═══════╪═══════╪═══╪═════╪═════╪══════╪══════╡
#> │ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
#> │ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
#> │ 22.8 ┆ 4.0 ┆ 108.0 ┆ 93.0  ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 1.0  │
#> │ 21.4 ┆ 6.0 ┆ 258.0 ┆ 110.0 ┆ … ┆ 1.0 ┆ 0.0 ┆ 3.0  ┆ 1.0  │
#> │ …    ┆ …   ┆ …     ┆ …     ┆ … ┆ …   ┆ …   ┆ …    ┆ …    │
#> │ 15.8 ┆ 8.0 ┆ 351.0 ┆ 264.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 4.0  │
#> │ 19.7 ┆ 6.0 ┆ 145.0 ┆ 175.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 6.0  │
#> │ 15.0 ┆ 8.0 ┆ 301.0 ┆ 335.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 8.0  │
#> │ 21.4 ┆ 4.0 ┆ 121.0 ┆ 109.0 ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 2.0  │
#> └──────┴─────┴───────┴───────┴───┴─────┴─────┴──────┴──────┘
#> groups: [[1]]
#> [1] "am"
#> 
#> maintain order:  FALSE

class(test2) <- "DataFrame"
test2
#> shape: (32, 11)
#> ┌──────┬─────┬───────┬───────┬───┬─────┬─────┬──────┬──────┐
#> │ mpg  ┆ cyl ┆ disp  ┆ hp    ┆ … ┆ vs  ┆ am  ┆ gear ┆ carb │
#> │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ --- ┆ --- ┆ ---  ┆ ---  │
#> │ f64  ┆ f64 ┆ f64   ┆ f64   ┆   ┆ f64 ┆ f64 ┆ f64  ┆ f64  │
#> ╞══════╪═════╪═══════╪═══════╪═══╪═════╪═════╪══════╪══════╡
#> │ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
#> │ 21.0 ┆ 6.0 ┆ 160.0 ┆ 110.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 4.0  ┆ 4.0  │
#> │ 22.8 ┆ 4.0 ┆ 108.0 ┆ 93.0  ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 1.0  │
#> │ 21.4 ┆ 6.0 ┆ 258.0 ┆ 110.0 ┆ … ┆ 1.0 ┆ 0.0 ┆ 3.0  ┆ 1.0  │
#> │ …    ┆ …   ┆ …     ┆ …     ┆ … ┆ …   ┆ …   ┆ …    ┆ …    │
#> │ 15.8 ┆ 8.0 ┆ 351.0 ┆ 264.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 4.0  │
#> │ 19.7 ┆ 6.0 ┆ 145.0 ┆ 175.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 6.0  │
#> │ 15.0 ┆ 8.0 ┆ 301.0 ┆ 335.0 ┆ … ┆ 0.0 ┆ 1.0 ┆ 5.0  ┆ 8.0  │
#> │ 21.4 ┆ 4.0 ┆ 121.0 ┆ 109.0 ┆ … ┆ 1.0 ┆ 1.0 ┆ 4.0  ┆ 2.0  │
#> └──────┴─────┴───────┴───────┴───┴─────┴─────┴──────┴──────┘
```

**Comment by vincentarelbundock** [comment]
Don't have any insight into this, but I wonder if there shouldn't be a better interface to this. Changing the class feels hackish. Perhaps a simple approach would be for `pl$DataFrame()` to convert the grouped object back to a standard polars data frame?

**Comment by etiennebacher** [comment]
The thing is there's no function that can be applied on a `GroupBy` object to ungroup it: https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/groupby.html

So even a mechanism like this is implemented in `r-polars` it will still be a hack and not something Polars support. I also didn't find any issues mentioning "ungroup" on the `rust-polars` repo.

**Comment by etiennebacher** [comment]
FYI this is why Python's `tidypolars` doesn't have `group_by()` but uses a `.by` argument instead: https://github.com/markfairbanks/tidypolars/issues/201

**Comment by eitsupi** [comment]
> FYI this is why Python's `tidypolars` doesn't have `group_by()` but uses a `.by` argument instead: [markfairbanks/tidypolars#201](https://github.com/markfairbanks/tidypolars/issues/201)

Perhaps it would be best to give up reproducing `group_by` and `ungroup` in R tidypolars as well?

I believe the `arrow` package had numerous bugs due to reproducing these. (For example apache/arrow#14175)

**Comment by etiennebacher** [comment]
FYI I think I found a solution for `tidypolars`: https://github.com/etiennebacher/tidypolars/pull/22
Just waiting for a PR in `r-polars`

**Comment by sorhawell** [comment]
@etiennebacher  I think what you are trying will work.

For reference the [rust-polars GroupBy](https://github.com/pola-rs/polars/blob/36833440ac1b86b25ea670b7a18f5b65b0c232f1/crates/polars-core/src/frame/groupby/mod.rs#L182) is implemented with a lifetime chained to the `DataFrame`. However, extendr does not support lifetime annotated structs. A `GroupBy` is just a reference to a `DataFrame` + some few options such `maintain_order`. In `r-polars` `GroupBy` is a "virtual class abstraction" on top of `DataFrame` + some modified attributes to remember options.

The r-polars `LazyFrameGroupBy` in rust-polars has not lifetime annotation and is wrapped as is in r-polars.


I think you could get far by not using `LazyFrameGroupBy` and instead working with attributes as r-polars `GroupBy`.

I have approved your `<LazyFrame>.clone()`PR #347  which is needed as it is the only to have immutable attributes for the ExternalPtr.
