### ISSUE TITLE
NOT_CRAN -> IS_CRAN?

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#339]
@eitsupi  would it be reasonable to move away from the NOT_CRAN  environment variable approach?

I know me and @Sicheng-Pan  are killing our cache by accident several times. It takes my computer 20 min per time to recompile. I think this will certainly be a hurdle for any new contributor.

Now when CRAN is not on the table, we could invert the settings to be a IS_CRAN setting? If CRAN ever comes on the table again, maybe it easier to have a dedicated release script, which modifies the makevars file or any other file.

**Comment by eitsupi** [comment]
> Now when CRAN is not on the table, we could invert the settings to be a IS_CRAN setting?

I do not know how to tell if it is on CRAN. (In other words, I consider such an approach impossible.)
CRAN does not set an environment variable called `IS_CRAN`, so it cannot detect one that is not set.

All we can do is to completely ignore the CRAN policy and not delete the detritus always (I think this will generate warnings from R)
https://github.com/pola-rs/r-polars/blob/c24eb71adceef431521c6f6af9acd0cbc6901bc3/src/Makevars#L27-L30
