### ISSUE TITLE
R cmd check fails with latest rust-polars on macOS

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#35]
Test PR  #34 shows r-polars fails R CMD check  on macOS if upgrading rust-polars dependency beyond [this polars commit](https://github.com/pola-rs/polars/pull/6156)

Windows:
Likely because polars included crate sysinfo which have a lot of system dependencies. For windows following mingw libraries -lntdll -lpsapi -liphlpapi -lpdh -lpowrprof -loleaut32 -lnetapi32 -lsecur32 can be included to the linker, and the problem is resolved.

However for macOS R CMD check throws the following error: 
```R
❯ checking whether the package can be unloaded cleanly ... WARNING
  Error: package or namespace load failed for ‘rpolars’ in dyn.load(file, DLLpath = DLLpath, ...):
   unable to load shared object '/Users/runner/work/r-polars/r-polars/check/rpolars.Rcheck/rpolars/libs/rpolars.so':
    dlopen(/Users/runner/work/r-polars/r-polars/check/rpolars.Rcheck/rpolars/libs/rpolars.so, 0x0006): symbol not found in flat namespace (_IOBSDNameMatching)
  Execution halted

❯ checking whether the namespace can be loaded with stated dependencies ... WARNING
  Error in dyn.load(file, DLLpath = DLLpath, ...) : 
    unable to load shared object '/Users/runner/work/r-polars/r-polars/check/rpolars.Rcheck/rpolars/libs/rpolars.so':
    dlopen(/Users/runner/work/r-polars/r-polars/check/rpolars.Rcheck/rpolars/libs/rpolars.so, 0x0006): symbol not found in flat namespace (_IOBSDNameMatching)
  Calls: <Anonymous> ... eval -> eval -> loadNamespace -> library.dynam -> dyn.load
  Execution halted
  
  A namespace must be able to be loaded with just the base namespace
  loaded: otherwise if the namespace gets loaded by a saved object, the
  session will be unable to start.
  
  Probably some imports need to be declared in the NAMESPACE file.

```

**Comment by sorhawell** [comment]
In the short run workflow will just ignore warnings/notes containing `_IOBSDNameMatching`. The macOS build still passes all unit tests.

I guess this could be resolved by figuring out what crate sysinfo is depending on and some how explicitly state this as a requirement in rpolars DESCRIPTION to satisft R CMD check.

**Comment by sorhawell** [comment]
r-polars works just fine for macOS. It is just matter figuring out if the rpolars relies on some system dependency and how to state this in the DESCRIPTION file. It could also be a false alarm, as rpolars is statically linked and all dependencies should be included in the binary.

**Comment by ghuls** [comment]
Not sure it objdump also works on Mac or if it is called differntly, but it might help if you can print all symbols.

```
objdump -T rpolars.so
```

**Comment by sorhawell** [comment]
thx I will try it out, seem there is a variant called otools which is recommended:
https://superuser.com/questions/206547/how-can-i-install-objdump-on-mac-os-x
