### ISSUE TITLE
Cache Rust dependencies in CI?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#360]
CI jobs go from 20min to more than 1h. What takes time is compiling `rust-polars` + all its dependencies, but since all of those are versioned dependencies, is it possible to cache them and share them between github actions?

Note that a second thing that takes time is that in some jobs, we compile twice: one when we build the package to test it, and one when we build the binary (see here for example: https://github.com/pola-rs/r-polars/actions/runs/5810787046/job/15752502201)

**Comment by sorhawell** [comment]
I think the cache is decided here https://github.com/pola-rs/r-polars/blob/8de9d98ad7c2af16da03d38638ebec95f70301b9/.github/actions/setup/action.yaml#L39

I don't know how this shared cache work actually

At best it takes 5 min on Ubuntu to run a check. caching on windows machines have never worked well and some windows build will often take 20-40 minutes

I have tried to fiddle alot with cache keys long time back. But never got really fast builds.

**Comment by eitsupi** [comment]
Yeah, `cargo build` is definitely only done once in all workflows right now.

Since the hash of `Cargo.toml` is the cache key, the cache will be empty when executed immediately after editing the `Cargo.toml` file.
