### ISSUE TITLE
Release 8.1 check list

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#387]
## already in main
    New string method to_titlecase() (#371).
    New vignette on best practices to improve polars performance (#188).
    Subnamespace name "arr" as in <Expr>$arr$ & <Series>$arr$ is deprecated in favor of "list". Finally at polars 0.9.0 the "arr" will be removed (#375).

## in PRs
#377   - add cross compilation

**Comment by etiennebacher** [comment]
I think you can release as soon as #377 is merged. The objective of this release is mostly to change the subnamespace, right? So it's fine if it only has few changes
