### ISSUE TITLE
Error when I use `pl$Datetime` 

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#389]
Using `pl.Datetime` in `strptime()` for example works in [py-polars](https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.str.strptime.html#polars.Expr.str.strptime) but not here:

``` r
library(polars)

pl$set_options(do_not_repeat_call = TRUE)

df = pl$DataFrame(date = c("2006-01-08 10:07:52"))

### Works with pl$Date
df$with_columns(
  pl$col("date")$str$strptime(pl$Date, "%Y-%m-%d %H:%M:%S", strict = FALSE)
)
#> shape: (1, 1)
#> ┌────────────┐
#> │ date       │
#> │ ---        │
#> │ date       │
#> ╞════════════╡
#> │ 2006-01-08 │
#> └────────────┘

### Works with pl$Datetime()
df$with_columns(
  pl$col("date")$str$strptime(pl$Datetime(), "%Y-%m-%d %H:%M:%S", strict = FALSE)
)
#> shape: (1, 1)
#> ┌─────────────────────┐
#> │ date                │
#> │ ---                 │
#> │ datetime[μs]        │
#> ╞═════════════════════╡
#> │ 2006-01-08 10:07:52 │
#> └─────────────────────┘

### Doesn't work with pl$Datetime
df$with_columns(
  pl$col("date")$str$strptime(pl$Datetime, "%Y-%m-%d %H:%M:%S", strict = FALSE)
)
#> Error: Execution halted with the following contexts
#>    0: In R: in str$strptime:
#>    1: arg datatype is not an RPolarsDataType
```

**Comment by sorhawell** [comment]
r-polars has implemented 3 composite DataTypes: DateTime, List, and Struct. These are not fully meaningful without a full specification of the inner types. On R side these are implemented as functions which create the final rust enum DataType e.g. 
```R
> pl$Struct(pl$List(pl$Int16),pl$UInt32)
DataType: Struct(
    [
        Field {
            name: "",
            dtype: List(
                Int16,
            ),
        },
        Field {
            name: "",
            dtype: UInt32,
        },
    ],
)
```

List and Struct contains recursively other DataType and if constructed without I think py-polars currently annotates these as "unknown". I don't know if that is particularly useful yet.

For pl$DataTime, it contains a TimeUnit and a TimeZone which has default, so pl$DateTime should simply be syntactic sugar for pl$DataTime()

```R
> pl$Datetime()
DataType: Datetime(
    Microseconds,
    None,
)
```

In rust and python there are traits and dunder methods which can be used to define what if referred to as a value or called as function. I'm missing a similar base functionality in R to derive that behavior.

I'm aware of this trick in R, but I'm not sure if it could be useful 

```R
> l = list(foo = \() 1, list(foo=2))
> with(l[[2]],foo)
[1] 2
> with(l[[2]],foo())
[1] 123

```

**Comment by etiennebacher** [comment]
I see, thank you for the explanation. I also don't know an easy way in R to have something that can be called with or without parenthesis and have different values based on that. It would probably be quite hackish and the benefit would be limited.

**Comment by sorhawell** [comment]
I realize it is actually possible to achieve this, "if Muhammed does not want to come to the mountain, it would be possible to move the mountain". It would just be a huge rewrite to do this.

Instead of making RPolarsDataType optional callable, then the composite DataType functions e.g. pl$DataType can be made behave like a value by sub classing the function with "RPolarsDataType" and everywhere in codebase make a RPolarsDataType is first tested if really a function, and then called  first, e.g. 

if done this is possible
```R
> pl$Datetime
DataType: Datetime(
    Microseconds,
    None,
)
> str(pl$Datetime)
function (tu = "us", tz = NULL)  
 - attr(*, "srcref")= 'srcref' int [1:8] 185 28 190 3 28 3 185 190
  ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x7fbd19be53d8> 
 - attr(*, "class")= chr [1:2] "RPolarsDataType" "function"
> pl$Datetime == pl$Datetime()
[1] TRUE
``` 

but every interacting with RPolarsDataType-class something like this must be used
```R
print.RPolarsDataType = function(x, ...) {
  cat("DataType: ")
  call_if_function(x)$print()
  invisible(x)
}

call_if_function = \(x) {
    if(is.function(x)) {
      x()
    } else {
      x
    }
}
```

similar robj_to!(RPolarsDataType,some_arg)! can be defined via something like 

```rust
pub fn robj_to_datatype(robj: extendr_api::Robj) -> RResult<RPolarsDataType> {
    let rv = rdbg(&robj);
    use extendr_api::*;
    // allow something inheriting RPolarsDataType to be function which returns a regular RPolarsDataType
    let robj = unpack_r_eval(R!("polars:::result(polars:::call_if_function({{robj}}))"))?;

    // try get internal rust-side polars DataType from a regular RPolarsDataType robj
    let res: ExtendrResult<ExternalPtr<RPolarsDataType>> = robj.try_into();
    let ext_dt = res.bad_val(rv).mistyped(tn::<RPolarsDataType>())?;
    Ok(RPolarsDataType(ext_dt.0.clone()))
}
```

The downside is that any use RPolarsDataType must be refactored and tidied alot to add big technical debt to the code base.
I started on this, but seems to be multi day project. Unless really, really needed, I [park the attempt in this branch](https://github.com/pola-rs/r-polars/commit/291d016e4cba286780f039e68fdd2745e5dae00a)
