### ISSUE TITLE
groupby -> group_by

### ISSUE THREAD

**Issue by grantmcdermott** [pola-rs/r-polars#406]
Just noticed the following `groupby` deprecation warning on py-polars.

> Deprecated since version 0.19.0: This method has been renamed to [LazyFrame.group_by()](https://pola-rs.github.io/polars/py-polars/html/reference/lazyframe/api/polars.LazyFrame.group_by.html#polars.LazyFrame.group_by).

Do we just want to alias with `group_by` for now?

P.S. A few related methods have also taken on this syntax change. See https://github.com/pola-rs/polars/pull/10656

**Comment by sorhawell** [comment]
nice spotted :) 


yeah some aliasing like this would do I guess

```R
# LazyFrame_groupby = function(. . .) {
LazyFrame_group_by = function(. . .) {
 . . .
}

LazyFrame_groupby(. . .) {
  warning("deprecation warning, method renamed to `$group_by()` old naming removed from polars 0.9.0")
  self$group_by(. . . )
}
```

**Comment by etiennebacher** [comment]
Note that it was also renamed on the Rust side: https://github.com/pola-rs/polars/pull/10654

This change was part of rust-polars 0.33

**Comment by eitsupi** [comment]
I opened a PR to update rust-polars (#417).
We probably can do this after #417 is merged as I will not be making any changes on the R side in #417.
