### ISSUE TITLE
Should we install the fork version of extendr?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#418]
A new version of extendr was recently released.

We are currently using a forked extendr, is this still necessary?
https://github.com/pola-rs/r-polars/blob/2d2aaa7386e869b53a55e4be11d3ea974d52de86/src/rust/Cargo.toml#L37-L40

**Comment by sorhawell** [comment]
I look through PRs to main in our fork. Most have been accepted, so shat should be possible now.

We should give up planned [renaming r-polars classes via this extendr PR](https://github.com/extendr/extendr/pull/553) and just use classic rust type aliasing instead, which is fine. We never implemented this so, we likely don't have to revert anything.

It could happen in future we wanna fork again. If so we should just release our own fork on crates.io also.

**Comment by etiennebacher** [comment]
> We should give up planned https://github.com/extendr/extendr/pull/553 and just use classic rust type aliasing instead, which is fine.

Just to be sure, you're talking about changing class names on the Rust side, right? It would still be useful to have more specific class names on the R side, for example:

* `DataFrame` -> `PolarsDataFrame`
* `LazyFrame` -> `PolarsLazyFrame`
* `Expr` -> `PolarsExpr`

We would only need to change the classes, not the way we call them in the docs

**Comment by eitsupi** [comment]
@sorhawell I agree that it is not necessary at this time.
However, there is a possibility that extendr/extendr#553 may be merged if tests are added?
(I think this feature is really great!)

> Just to be sure, you're talking about giving up changing class names on the Rust side, right?

Yes, this issue extendr/extendr#536.

Is this what actually determines the name of the `DataFrame` class on the R side?
https://github.com/pola-rs/r-polars/blob/abb4bd1c4c680aae70c8f5a750b7746c1bed4259/R/dataframe__frame.R#L68-L78

**Comment by sorhawell** [comment]
I started PR #253  "try use extendr PR553 to rename classes" and my feeling was the codebase become less intuitive to navigate.

I think the renaming should happen, and I will applaud any PR that make it so.
@Sicheng-Pan  [just started to rename e.g. the r-polars `DataFrame` for `RDF`](https://github.com/pola-rs/r-polars/blob/abb4bd1c4c680aae70c8f5a750b7746c1bed4259/src/rust/src/rbackground.rs#L2) in some modules via type rust aliasing. In such case we will literally name all rust wrapper structs by the intended class name in R. Then we at the same time give them a type alias e.g. RDataFrame, RExpr, which will be used as their de-facto name on rust side.

It appears to me that is a simpler approach which is also worth exploring. If that for some reason does not work, extendr-PR553 should come through.

**Comment by sorhawell** [comment]
> Is this what actually determines the name of the DataFrame class on the R side?

yes via extendr-api reads the name of the struct on rust side and generates function which rextendr calls and then writes 

```R
.
.
.

DataFrame <- new.env(parent = emptyenv())

DataFrame$shape <- function() .Call(wrap__DataFrame__shape, self)

DataFrame$n_chunks <- function(strategy) .Call(wrap__DataFrame__n_chunks, self, strategy)

DataFrame$rechunk <- function() .Call(wrap__DataFrame__rechunk, self)
.
.
.

```

553 can change the name on R side, but for r-polars we may be happier by literally renaming the

today rust and R name DataFrame.
```rust
struct DataFrame(pl::DataFrame);

#[extendr]
impl DataFrame {...}
```

use alias solution rust name RDataFrame, R class name RPolarsDataFrame
```rust
struct RPolarsDataFrame(pl::DataFrame);
use RPolarsDataFrame as RDataFrame;

#[extendr]
impl DataFrame {...}
```
PR553 solution rust name RDataFrame, R class name RPolarsDataFrame
```rust
struct RDataFrame(pl::DataFrame);

#[extendr(r_name = "RPolarsDataFrame")]
impl RDataFrame {...}
```

**Comment by eitsupi** [comment]
Thank you for your detailed explanation.

As I wrote in #149, I thought it was bad that if we select `RDataFrame` on the Rust side, it also looks like `RDataFrame` on the R side, but I think it's a good compromise to use `RPolarsDataFrame` in both Rust and R.

- `RDataFrame` on the Rust side is reminiscent of R's `data.frame`, so it might not be a very good name.
- `PolarsDataFrame` on the R side may also cause confusion as to whether it is an r-polars' struct or rust-polars' struct (?)

**Comment by sorhawell** [comment]
> but I think it's a good compromise to use RPolarsDataFrame in both Rust and R.

Yeah that would probably be fine. A little verbose, but very simple.

> RDataFrame on the Rust side is reminiscent of R's data.frame, so it might not be a very good name.

true, py-polars call their wrapper PyDataFrame

> PolarsDataFrame on the R side may also cause confusion as to whether it is an r-polars' struct or rust-polars' struct (?)

With extendr the current r-polars struct that we currently call "DataFrame" which is the simplest possible wrapper around the rust-polars struct is the minimal porting into R. Their could not be a more "naked" rust-polars accessed from so either PolarsDataFrame or RPolarsDataFrame would be fine on R side. On rust side PolarsDataFrame is confusing though.


OK fall back plan could be prefix all structs / classes "RPolars". That will work.

Optionally choose a shorter use alias on rust side like "RDataFrame" or "RPDataFrame" or "RDF"  likewise "RSeries", "RPSeries" and "RS"(probably not good).

**Comment by etiennebacher** [comment]
> I think it's a good compromise to use RPolarsDataFrame in both Rust and R.

Agreed (with the other classes starting with `RPolars`, for example `RPolarsExpr`).

**Comment by eitsupi** [comment]
I tried to replace to extendr 0.6.0, but there seems to be an error in the following location. This part differs from the fork.......

```log
   error[E0433]: failed to resolve: use of undeclared crate or module `extendr_api`
      --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/extendr-api-0.6.0/src/robj/into_robj.rs:159:22
       |
   159 |             Ok(x) => list!(ok = x, err = NULL),
       |                      ^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `extendr_api`
       |
       = note: this error originates in the macro `list` (in Nightly builds, run with -Z macro-backtrace for more info)
   help: consider importing this struct through its public re-export
       |
   1   + use crate::List;
       |
   
   error[E0433]: failed to resolve: use of undeclared crate or module `extendr_api`
      --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/extendr-api-0.6.0/src/robj/into_robj.rs:159:22
       |
   159 |             Ok(x) => list!(ok = x, err = NULL),
       |                      ^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `extendr_api`
       |
       = note: this error originates in the macro `list` (in Nightly builds, run with -Z macro-backtrace for more info)
   help: consider importing this struct through its public re-export
       |
   1   + use crate::Robj;
       |
   
   error[E0433]: failed to resolve: use of undeclared crate or module `extendr_api`
      --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/extendr-api-0.6.0/src/robj/into_robj.rs:165:17
       |
   165 |                 list!(ok = NULL, err = err_robj)
       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `extendr_api`
       |
       = note: this error originates in the macro `list` (in Nightly builds, run with -Z macro-backtrace for more info)
   help: consider importing this struct through its public re-export
       |
   1   + use crate::List;
       |
   
   error[E0433]: failed to resolve: use of undeclared crate or module `extendr_api`
      --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/extendr-api-0.6.0/src/robj/into_robj.rs:165:17
       |
   165 |                 list!(ok = NULL, err = err_robj)
       |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `extendr_api`
       |
       = note: this error originates in the macro `list` (in Nightly builds, run with -Z macro-backtrace for more info)
   help: consider importing this struct through its public re-export
       |
   1   + use crate::Robj;
       |
   
      Compiling value-trait v0.6.1
      Compiling comfy-table v7.1.0
      Compiling serde_json v1.0.107
   error[E0599]: the method `into_robj` exists for type parameter `E`, but its trait bounds were not satisfied
      --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/extendr-api-0.6.0/src/robj/into_robj.rs:161:34
       |
   152 | impl<T, E> From<std::result::Result<T, E>> for Robj
       |         - method `into_robj` not found for this type parameter
   ...
   161 |                 let err_robj = x.into_robj();
       |                                  ^^^^^^^^^ method cannot be called on `E` due to unsatisfied trait bounds
       |
      ::: /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/extendr-api-0.6.0/src/robj/mod.rs:111:1
       |
   111 | pub struct Robj {
       | ---------------
       | |
       | doesn't satisfy `robj::Robj: From<&E>`
       | doesn't satisfy `robj::Robj: From<&mut E>`
       | doesn't satisfy `robj::Robj: From<E>`
       |
   note: the following trait bounds were not satisfied:
         `robj::Robj: From<&E>`
         `robj::Robj: From<&mut E>`
         `robj::Robj: From<E>`
      --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/extendr-api-0.6.0/src/robj/into_robj.rs:203:11
       |
   201 | impl<T> IntoRobj for T
       |         --------     -
   202 | where
   203 |     Robj: From<T>,
       |           ^^^^^^^ unsatisfied trait bound introduced here
   note: the trait `From` must be implemented
      --> /usr/local/rustup/toolchains/nightly-2023-08-26-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:538:1
       |
   538 | pub trait From<T>: Sized {
       | ^^^^^^^^^^^^^^^^^^^^^^^^
   
   Some errors have detailed explanations: E0433, E0599.
   For more information about an error, try `rustc --explain E0433`.
   error: could not compile `extendr-api` (lib) due to 5 previous errors
```

https://github.com/rpolars/extendr/blob/d06f3bc96b168dae1a63f6e625c5bf80e98adc1b/extendr-api/src/robj/into_robj.rs#L142-L165
https://github.com/extendr/extendr/blob/630a7e2289d2a26c9beee29542049d67c7515e64/extendr-api/src/robj/into_robj.rs#L151-L174

Perhaps the test does not exist in extendr main and the wrong implementation has not been corrected?

@sorhawell Could you correct this on the extendr side?
Sorry, but the commit history is too hard to read and I don't understand what is changed in the default branch and fork of extendr.

I know it takes a very long time to merge and release on the extendr side, but unless this is fixed we will have to maintain the fork forever.

**Comment by sorhawell** [comment]
@eitsupi 

When I submitted "Result"-PR, I remember extendr reviewer preferred some minor changes in conversions which is the difference between fork and the main.


extendr-api have three different conversions traits 

[Two blanket impls 
Into<U> + TryInto<U>](https://extendr.github.io/extendr/extendr_api/robj/struct.Robj.html)
[and also IntoRobj](https://extendr.github.io/extendr/extendr_api/robj/into_robj/trait.IntoRobj.html)

There are some tiny differences it would conversions are supported. But it should be something we work around easily.
I thought IntoRobj would be deprecated at some point, but either should be fine.

I could not see it in the error log, but Extendr have some new breaking changes in floating point conversions we might run into, but there is posted compatibility around on that ...

**Comment by eitsupi** [comment]
@sorhawell Thank you for looking at this. Please rest at ease, take care.
