### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#443]
@sorhawell @etiennebacher There is a large number of old branches on GitHub that have not had their PRs opened.
If you do not use these, could you please delete them? I don't see the need for them.

![image](https://github.com/pola-rs/r-polars/assets/50911393/44624a11-db1a-4da4-a367-d2105f68da7d)

**Comment by etiennebacher** [comment]
Done for me, the others are either draft PRs or were opened by @sorhawell so I don't know which ones can be deleted.

**Comment by sorhawell** [comment]
Some of the branches have some sentimental value to me. I will migrate them to my own fork.

**Comment by eitsupi** [comment]
It seems cleaned up, thanks!
