### ISSUE TITLE
Code copied from the data.table package

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#460]
https://github.com/pola-rs/r-polars/blob/0e730bccb48a0126283235cbe3834f57ae678fcd/R/translation.R#L1-L2

If I understand correctly, the data.table package is licensed under the MPL-2.0 license, so distributing it as an MIT license is a license violation.

**Comment by etiennebacher** [comment]
We could simply remove those. A lot of messages come from Rust anyway and will be in English
