### ISSUE TITLE
0.10.0 release

### ISSUE THREAD

**Issue by grantmcdermott** [pola-rs/r-polars#466]
I know that 0.9.0 just came out earlier in the week. But can I selfishly nudge for a 0.9.1 patch release? This is mostly to catch https://github.com/pola-rs/r-polars/pull/442, which in turn will allow me to demonstrate hive-dataset I/O for an internal workshop that I'm giving at work.

Again don't feel obliged to rush a patch release. But it would be nice for me to demonstrate the same functionality across both the R and Python Polars implementations.

**Comment by eitsupi** [comment]
I think this should be 0.10 as it is a breaking change.

**Comment by etiennebacher** [comment]
I think so too and it would be nice if #455 could be included since it's close to being complete. In a sense that would be enough new things to justify a new release but it feels a bit weird to have two "major" releases in a week

**Comment by grantmcdermott** [comment]
Cool, don't stress if it's going to be a more than a patch release. I'll tell my audience that this functionality is just around the corner...

Will close this then if the next release is going to be be 0.10.

**Comment by eitsupi** [comment]
I don't think frequent major releases are a problem here, as this package cannot be submitted to CRAN at this stage.
So I'm happy to be able to release 0.10 in the next week or so.

Note that thanks to the new binary release mechanism, it is now possible to quickly install a specific version from GitHub.

```r
> Sys.setenv(NOT_CRAN="true")
> Sys.setenv(PKG_SYSREQS="false")
> pak::pak("pola-rs/r-polars@v0.9.0")

→ Will install 1 package.
→ Will download 1 package with unknown size.
+ polars   0.9.0 [bld][cmp][dl] (GitHub: d3c0b03) + ✖ cmake, ✖ rustc, ✖ cargo
✖ Missing 3 system packages. You'll probably need to install them manually:
+ cargo  - polars
+ cmake  - polars
+ rustc  - polars
ℹ Getting 1 pkg with unknown size
✔ Cached copy of polars 0.9.0 (source) is the latest build
✔ No downloads needed, all packages are cached
ℹ Packaging polars 0.9.0
✔ Packaged polars 0.9.0 (2.6s)
ℹ Building polars 0.9.0
✔ Built polars 0.9.0 (42.2s)
✔ Installed polars 0.9.0 (github::pola-rs/r-polars@d3c0b03) (734ms)
✔ 1 pkg + 1 dep: kept 1, added 1 [47.9s]
```

**Comment by etiennebacher** [comment]
All good for me, #470 is not ready. Go ahead with 0.10.0
