### ISSUE TITLE
Split README.md to some docs

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#485]
- [x] `DEVELOPMENT.md` for developers to develop this package. (#538, #586)
- [x] `vignettes/install.Rmd` for users to install this package. (#643)

**Comment by etiennebacher** [comment]
I'm not convinced we need a vignette for installation instructions, this should appear in the README. Also the procedure is simpler now thanks to your improvements with the binaries, right?

**Comment by eitsupi** [comment]
> I'm not convinced we need a vignette for installation instructions, this should appear in the README.

My intention is something like the arrow package has.
<https://arrow.apache.org/docs/r/articles/install.html>

In my opinion the installation details are too long to write in the README.

**Comment by etiennebacher** [comment]
I'm fine with having a vignette for more detailed instructions, but I'd still want to keep basic installation instructions on the README. I often go to the website homepage just to copy the `install.packages()` line
