### ISSUE TITLE
groupby_rolling documentation mentioned but not linked

### ISSUE THREAD

**Issue by jangorecki** [pola-rs/r-polars#513]
`groupby_rolling` is mentioned in documentation multiple times, without linking. Search function in online docs does not find it either.

Would be nice to have working links in documentation whenever a function (at least from the same package) is mentioned.

**Comment by etiennebacher** [comment]
> `groupby_rolling` is mentioned in documentation multiple times, without linking. Search function in online docs does not find it either.

Indeed, it is not implemented yet but I'm working on it in https://github.com/pola-rs/r-polars/pull/470. Note that `groupby_rolling()` was deprecated in favor of `rolling()` in python-polars (https://github.com/pola-rs/polars/pull/11761) so I implement it as `rolling()` directly.

> Would be nice to have working links in documentation whenever a function (at least from the same package) is mentioned.

Yes, I'd like to tackle this eventually but there are many easier docs improvements before this.

**Comment by etiennebacher** [comment]
@jangorecki `$rolling()` is now available in the development version. It's not the kind of feature I use a lot so it would be great to know if it works fine for you. I'll open a separate issue for linking functions in the docs.
