### ISSUE TITLE
Update `pl$concat()`'s arguments

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#520]
See <https://github.com/pola-rs/polars/blob/0c56f9b3eae1f28e1d09b6f3bc00c9c3fbdc5847/py-polars/polars/functions/eager.py#L22-L240>

**Comment by etiennebacher** [comment]
This was actually made on purpose in https://github.com/pola-rs/r-polars/pull/407 

But we should match py-polars syntax so I'll change this. Are you fine with that @sorhawell ?
