### ISSUE TITLE
Allow `$filter` and `$when` for `df$filter(x = 1, y = 2)` like syntax (like in `$select`)

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#532]
Recently py-polars allows this in filter, and I saw a PR opened to introduce it when as well (pola-rs/polars#12603).

**Comment by etiennebacher** [comment]
I like that we wouldn't have to use `pl$col()` anymore there, but having a single `=` looks very weird to me, all comparisons in R require `==`. Maybe it's different in Python but I think that's something that we can do differently.

**Comment by eitsupi** [comment]
> I like that we wouldn't have to use `pl$col()` anymore there, but having a single `=` looks very weird to me, all comparisons in R require `==`.

Agree.

> Maybe it's different in Python but I think that's something that we can do differently.

I think to omit `pl.col()` we have to set the column name as a name of object.
We could simply not allow this and only allow multiple conditions to be placed with commas.

**Comment by sorhawell** [comment]
For LazyFrame and DataFrame we could from all column names mentioned in schema produce column expressions which are named by the column name e.g.

cyl = pl$col("cyl")


Then one could write 
$filter(cyl==4, hp>80)

**Comment by eitsupi** [comment]
The ability to select columns by NSE would make writing queries much easier, but I feel it is better not to do this here to keep the `polars` package simple.
Wouldn't it be better to achieve this with a downstream package like `tidypolars` combined with a good package like `rlang`?

**Comment by etiennebacher** [comment]
Yes, I have already worked a lot on NSE in another data wrangling package and there are many corner cases to avoid. The current syntax, while verbose, is also much safer.

>  Wouldn't it be better to achieve this with a downstream package like tidypolars combined with a good package like rlang?

`tidypolars` already works with all selecting patterns and select helpers of `tidyselect`

**Comment by eitsupi** [comment]
Closing in favor of #598
