### ISSUE TITLE
how to force evaluation to avoid laziness

### ISSUE THREAD

**Issue by jangorecki** [pola-rs/r-polars#535]
Sorry for asking question here but documentation is barely usable (hope it will improve soon).
How to force evaluation? so there is no doubt if any part of computation might have been still queued.
I can of course do as.data.frame, but that's probably carry extra overhead. So question is precisely how to force evaluation but not add unnecessary overhead.

.
..
...
ok, found collect()

**Comment by etiennebacher** [comment]
FYI I agree the "Reference" section on the website is still messy in some sections (working on this but it's a lot) but the vignettes should give you enough information to start: https://rpolars.github.io/articles/polars

**Comment by eitsupi** [comment]
I think contribution to improving the documentation would be very much appreciated!
