### ISSUE TITLE
Rendering bugs in the website

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#536]
I saw some rendering bugs in the current website.

- `&` in examples in Rd file
  https://github.com/pola-rs/r-polars/blob/da0809f6d094cd8ed3aab01467c50ddaa8c96b1b/man/Expr_and.Rd#L18-L21
  ![examples](https://github.com/pola-rs/r-polars/assets/50911393/e9a8d588-7310-4b6e-b351-4b93b86d2de6)
- `\code{}` in Rd file title
  https://github.com/pola-rs/r-polars/blob/da0809f6d094cd8ed3aab01467c50ddaa8c96b1b/man/Expr_eq_missing.Rd#L5
  ![code](https://github.com/pola-rs/r-polars/assets/50911393/bd0fe7eb-87ea-4df4-aa60-98fd39be8e5d) 
- GitHub issue links in the NEWS file
  https://github.com/pola-rs/r-polars/blob/da0809f6d094cd8ed3aab01467c50ddaa8c96b1b/NEWS.md?plain=1#L65-L67
  ![markdownlink](https://github.com/pola-rs/r-polars/assets/50911393/efb83a26-db3b-4a71-bc8f-6d4367e6ae69)

**Comment by etiennebacher** [comment]
> GitHub issue links in the NEWS file

https://github.com/etiennebacher/altdoc/issues/118

**Comment by eitsupi** [comment]
These issues seem fixed by #540, thanks!

...and there are new issues #605 now.
