### ISSUE TITLE
Mention extensions in the README?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#537]
So far I think  `polarssql` and `tidypolars`  are the only extensions based on `polars`

**Comment by eitsupi** [comment]
I wanted to work on this. Like the following:

````md
This package provides three APIs.

1. Method chaining using `$`, similar to Python polars' method chaining using `.`.
  ```r
  pl$DataFrame(mtcars)$select("cyl")
  ```
2. S3 methods for base R functions
  ```r
  as_polars_df(mtcars)[, "cyl", drop = FALSE]
  ```
3. SQL API (Please check the document for details)

Also, the following packages provide additional APIs

1. `{tidypolars}` provides `{dplyr}` backend.
2. `{polarssql}` provides `{DBI}` backend and `{dbplyr}` backend.
````

**Comment by etiennebacher** [comment]
Sounds good, just 2 remarks:

* there is only a limited number of S3 methods
* tidypolars provides a tidyverse backend (not only dplyr)

**Comment by eitsupi** [comment]
> * there is only a limited number of S3 methods

Yes, good point.
There is already a similar description below, so I think it's best to keep the amount written in the README to a minimum and link to the vignette.

https://github.com/pola-rs/r-polars/blob/da0809f6d094cd8ed3aab01467c50ddaa8c96b1b/vignettes/polars.Rmd#L168-L174
