### ISSUE TITLE
polars slow rolling

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#549]
As benchmarked [here ](https://github.com/jangorecki/rollbench/pull/1) by @jangorecki. Polars ~~has no optimized implementations for rolling mean, sum,~~ ... and is therefore quite slower than data.table. [I wrote imlps for sum/mean i32/i64/f32/f64/](https://github.com/pola-rs/r-polars/compare/fast_roll_prototype) and they are just as fast as data.table `froll_` if compiling with lto="fat".

I will look into how difficult it is to implement in native rust-polars, otherwise should we implement fast roll implementations in r-polars only?

**Comment by eitsupi** [comment]
I recommend that you do not create links to branches, as they are likely to be deleted in the future. It's safer to use the commit ID instead.

**Comment by etiennebacher** [comment]
> should we implement fast roll implementations in r-polars only?

They are already working on improving the rolling median algorithm, I think we can wait for that

**Comment by sorhawell** [comment]
> I recommend that you do not create links to branches, as they are likely to be deleted in the future. It's safer to use the commit ID instead.

So if I delete the branch this commit still exists in the repository? Or should it by parked in a closed PR?
https://github.com/pola-rs/r-polars/commit/f5d322e64760ce367c4ee6f698d0154cacfeecb6

**Comment by etiennebacher** [comment]
This was dealt with upstream and the latest improvements will be merged in #601
