### ISSUE TITLE
Rd files for internal functions?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#557]
I noticed that there are Rd files that are not displayed on the website. I think these documents need to be improved and put on the website.

**Comment by etiennebacher** [comment]
Do you have some examples of functions that are not shown?

**Comment by etiennebacher** [comment]
But should this appear on the website? Most S3 methods are useful but this one is just for autocompletion, I don't think it needs to be exposed in the docs

**Comment by etiennebacher** [comment]
Oh yes I think we can
