### ISSUE TITLE
Should we use `...` in methods that use several arguments of the same type?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#572]
Raised here: https://github.com/pola-rs/r-polars/pull/558#discussion_r1414526155

This would force the user to use named arguments.

Pros:

* safer especially when several args can take `TRUE` or `FALSE`

Cons: 

* longer to type (especially since we don't have autocompletion after the second `$`)
* important breaking change because existing code would have to be rewritten with the argument names. For some time, we would need some warning if the user passes unnamed args in `...`, otherwise they would silently be absorbed. I'd say this warning should be here for two releases at least given the size of the breaking change.

If we decide to go for this, we need to be consistent about where we implement it. It is useless to add this when we have two arguments and one can take a string and the other a numeric value since this will error on the Rust side. I only see benefits when several args have the same type.

@sorhawell @eitsupi what do you think?

**Comment by sorhawell** [comment]
I think py-polars has similar considerations and uses a star to block accessing parameters without spelling them out. E.g.
https://pola-rs.github.io/polars/py-polars/html/reference/dataframe/api/polars.DataFrame.join.html

We can choose to just match whatever py-polars. Wherever theres is a arg * only there to vacum up unnamed arguments, we can do the same with ...

py-polars like sometimes to 1-3 args then * the remaining args.


It is pity R does not support autocomplete for functions. It actually does with `[]`-syntax which is just a function under the hood.
I have a prototype where auto completion does work. But the syntax will look like this
`pl[]col[]head[10]alias[]`
That is the reason auto-completion works well for data.table.

**Comment by etiennebacher** [comment]
> Wherever theres is a arg * only there to vacum up unnamed arguments, we can do the same with `...`

Didn't know that, thanks

> pl[]col[]head[10]alias[]

I'm not too convinced by this syntax 😄 

I had explored a bit why we can't have autocompletion after the second `$` and I think the reason is that in order to propose the right choices, the IDE first has to evaluate internally the LHS of `$`. Problem: this evaluation could take a very long time depending on what is on the LHS so it is not done automatically. I don't know why `[]` behaves differently, though. Do you have a branch/repo where you implemented your prototype?

**Comment by sorhawell** [comment]
> This argument seems quite reasonable, but can we argue it somewhere else? (Bugzilla or someplace like https://github.com/r-devel/rcwg/issues?)

You're right.

Sry I have highjacked this issue. I will start a new issue, and try to a some point file a bugreport.

**Comment by etiennebacher** [comment]
I don't see an interest in keeping this issue open. The answer is basically "yes we should use `...` wherever py-polars uses `*`"
