### ISSUE TITLE
Is it worth continuing to use `=` for the assignment operator of R?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#590]
Currently this repository uses `=` for the R assignment operator, but I think this is detrimental to the developer experience because it is very time consuming to have to execute the `styler` twice to maintain it.
I suppose this used to be useful for copying and pasting code from py-polars, but now there is almost no need to copy large amounts of Python source code from py-polars, so I think there is little value in maintaining this style.

I think there would be a win if all assignment operators were rewritten to `<-` to allow a single subsequent execution of `styler`.

@sorhawell @etiennebacher Thoughts?

**Comment by sorhawell** [comment]
Im happy someone wrote an auto-formatter, but reading through the source code I do understand why styler in generel is slow. I feel tempted to re-write it in rust or Rcpp

I guess we can make 3 line change here and it should work. Maybe this is a simpler approach than styler.equals package.
https://github.com/r-lib/styler/blob/main/R%2Frules-tokens.R#L1

**Comment by eitsupi** [comment]
That is perfectly true, but the reality is that time constraints exist and I don't think it's worth it to stick with `=` until we maintain a large amount of time or styler forks.

**Comment by etiennebacher** [comment]
I mostly use `<-` in my workflow so I have no problem with removing `=` here.

> I feel tempted to re-write it in rust or Rcpp ... if there was a lot of time in life.

FYI I started an alternative to `lintr` in a private repo that uses a Rust library under the hood. Happy to share it with you if you're interested (but I also don't have time to work on this for now). Agreed that a lightning-fast formatter/linter like `ruff` for python would be amazing

**Comment by sorhawell** [comment]
I have been looking into the source code and vignettes of styler. It appears I have gotten it all wrong. My impression from stack-overflow answers and styler.equals is that it was difficult to customize some of the rules. I see now it is fairly easy to modify or add transformers and we can do the official styler package. 
other improvements

 - parallelize files to style
 - use file timestamps to decide if a file needs styling
 - make it fast and easy to style it all
 - add CI check if all files are styled

I will try to write up a PR

**Comment by lorenzwalthert** [comment]
Maintainer of {styler} here (and python polars user). Happy to help out if you need.

**Comment by sorhawell** [comment]
@lorenzwalthert thx for the help on setting up a derived style : https://github.com/r-lib/styler/issues/1170

I think I'm quite close with a PR now.

**Comment by sorhawell** [comment]
@eitsupi 

[this is a very brief style derived from tidyverse and fully compatible with the styler package](https://github.com/pola-rs/r-polars/blob/e8e4a555635441b17b7c5ae145ee3b09a5a2dc5e/tools/styler/styler_utils.R#L2)

 - This style can be used with any styler function such as `styler_pkg()` or `styler_files().
 - The rpolars_style is just as fast the tidyverse_style.
 - the current use of git diff in out makefile is likely not optimal I have write `style_files()`
   - support parallel load balanced styling 60-90 sec to cold style everything, thereafter 20 sec
   - does not open a process for each file
   - can use both `git diff` and `git status` to infer changes. Maybe also untracked files in future.
   - styling 8 small and big files takes now about 8 seconds


We should add a style check to our CI. If any file is modified when styling, it will count as a CI build error.


### some example code

```R
source("tools/styler/styler_utils.R")

# all 125 files
paths = list.files(".", recursive = TRUE, pattern = "\\.R$|\\.Rmd$", full.names = TRUE) |>
  setdiff("extendr-wrappers.R")
sum(file.info(paths)$size) / 1e3 # ~1.1 million characters

# style everything ~60-90 sec on a slow macbook
system.time({
  outputs = style_files(paths, do_parallel = TRUE, ncpu = 4)
})

# style everything again takes me about 25 sec, due to styler cache
system.time({
  outputs = style_files(paths, do_parallel = TRUE, ncpu = 4)
})


# use gitdiff to decide what let's say 8 modified files (including the big dataframe__frame.R)
# just add empty lines in buttom to trigger git diff
some_paths = list.files("R", recursive = TRUE, pattern = "\\.R$", full.names = TRUE) |>
  setdiff("extendr-wrappers.R") |>
  head(8) |>
  print()

#style_files uses git diff + git status to find new files, untracked files could also be added.
for (i in some_paths) writeLines(c(readLines(i), "\n \n"), i)
style_files( do_parallel = TRUE) |>
  system.time()
})

```

**Comment by etiennebacher** [comment]
I think this was taken care of in #608
