### ISSUE TITLE
question: how to generate the r-polars.pdf manual?

### ISSUE THREAD

**Issue by ssh352** [pola-rs/r-polars#593]
tried `devtools::build_manual` in the source root, with error generated

```
> devtools::build_manual(pkg=".",path="/tmp")
Error in `value[[3L]]()`:
! Failed to build manual
```

**Comment by etiennebacher** [comment]
I can reproduce, and running `R CMD Rd2pdf "."` in the terminal also errors with `unable to run 'makeindex' on 'Rd2.idx'`.

Running `tinytex::tlmgr_install("makeindex")` fixed the error.

Related SO question: https://stackoverflow.com/questions/69847540/devtoolsbuild-manual-error-failed-to-build-manual

@ssh352 can you try and let us know if it solved the issue for you too?

**Comment by ssh352** [comment]
@etiennebacher Hi the post didn't solve the issue. I generate the manual pdf for other R packages with out issue though.
