### ISSUE TITLE
`otherwise` is not optional in r-polars's when-then

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#599]
```r
> library(polars)
> pl$when(pl$col("foo") > 2)$then(1)$alias("val")
Error: syntax error: alias is not a method/attribute of the class Then 
 when calling method:
 pl$when(pl$col("foo") > 2)$then(1)$alias
```

In py-polars

```python
>>> import polars as pl
>>> pl.when(pl.col("foo") > 2).then(1).alias("val")
<polars.expr.expr.Expr object at 0x7fa5ee7cc0a0>
```

**Comment by etiennebacher** [comment]
See discussion in #707. At the moment this cannot be fixed.

**Comment by eitsupi** [comment]
I'd like to keep it open because I might be able to solve it someday.

**Comment by eitsupi** [comment]
> 2\. Call something like `as_polars_expr` in something like `pl$select` to convert `Then` class object to `Expr`. This allows to use Then class object in `pl$select`

I noticed that the code for this is here.
It seems it has not worked since the class names were changed because the test did not exist.
https://github.com/pola-rs/r-polars/blob/750f3246338d81d8a5b0db0dde95793dd03a3a97/src/rust/src/lazy/dsl.rs#L164-L166
