### ISSUE TITLE
Latest website rendering issues

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#605]
After #540, it seems that there are some issues on the website.

## Complex details seem broken

https://rpolars.github.io/man/Expr_when_then_otherwise/

![image](https://github.com/pola-rs/r-polars/assets/50911393/42506a09-a51b-49b4-830e-21db01109489)

https://github.com/pola-rs/r-polars/blob/8aabbab7f8e36846c4b4d41ea80250e83db73bc8/man/Expr_when_then_otherwise.Rd#L25-L52

## Articles are not found

https://rpolars.github.io/vignettes/

![image](https://github.com/pola-rs/r-polars/assets/50911393/d5843d8b-7d2d-4c2e-8fbd-a4ebd8813571)

**Comment by etiennebacher** [comment]
Thanks I'm taking a look

**Comment by eitsupi** [comment]
And, this may be a matter of preference, but examples now puts the code and results in separate code blocks, but I like pkgdown-like format that displays the results as comments in one code block like before.
I think that in the current state it may be difficult to tell the difference between the code and the result.

**Comment by etiennebacher** [comment]
> examples now puts the code and results in separate code blocks, but I like pkgdown-like format that displays the results as comments in one code block like before.

Thanks, I opened #610 for this
