### ISSUE TITLE
Re-style code output

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#610]
From #605 

> And, this may be a matter of preference, but examples now puts the code and results in separate code blocks, but I like pkgdown-like format that displays the results as comments in one code block like before.
> I think that in the current state it may be difficult to tell the difference between the code and the result.

This can be fixed in two steps:

* add a custom quarto preamble in `altdoc/preamble_man_qmd.yml` that contains:

```
knitr: 
  opts_chunk: 
    comment: "#>"
```
* add custom CSS in `altdoc/stylesheets/extra.css` to stick the `pre` tags of code and output together

**Comment by etiennebacher** [comment]
@eitsupi what do you think about something like this? 

![image](https://github.com/pola-rs/r-polars/assets/52219252/d3105069-cfaf-4417-baba-cc9936e004b0)

Problem if we stick the code blocks together is that there will be multiple "copy code" buttons. I kinda like the style in this example

**Comment by eitsupi** [comment]
Thanks. I think it is better.
