### ISSUE TITLE
Rewrite `<DataFrame>$describe`

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#614]
https://github.com/pola-rs/polars/blob/40d3e0818408d836abf6c31146a3f69fd628f0fb/py-polars/polars/dataframe/frame.py#L4305-L4434

**Comment by eitsupi** [comment]
Related upstream issue pola-rs/polars#13199

**Comment by etiennebacher** [comment]
They won't implement it in Rust so need to do this in R
