### ISSUE TITLE
website render issue of the changelog page

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#632]
I built the website and realized that toc is not generated as expected.
Maybe altdoc needs to change the header level?
![image](https://github.com/pola-rs/r-polars/assets/50911393/eadda28f-90ba-4fef-9b9a-307baaebde47)

_Originally posted by @eitsupi in https://github.com/pola-rs/r-polars/pull/631#discussion_r1437667459_

**Comment by eitsupi** [comment]
The issue of `usethis::use_version` r-lib/usethis#1930

**Comment by etiennebacher** [comment]
They're apparently not going to do it and the current setup works, I think this can be closed
