### ISSUE TITLE
Conversion from (nano)arrow ?

### ISSUE THREAD

**Issue by eddelbuettel** [pola-rs/r-polars#64]
The Arrow C interface is bidirectional. Having the the _export_ to (nano)arrow Table and RecordBatch is useful. It would also be nice to vbe able to go the other way and take a Arrow schema and array_data pointer pair to instantiate a polars instance.  

Are there any plans for this?    (If there are any I apologize. I looked and only found _export_ but not _import_.)

**Comment by sorhawell** [comment]
Hi Dirk, thank you for asking :) I think that would be the  [DataFrame.from_arrow()](https://github.com/pola-rs/polars/blob/master/py-polars/polars/convert.py#L308-L390) and that I need to implement.  I will try to do so right now.

**Comment by sorhawell** [comment]
uhh I hit a steep bump on my learning path on pointer magic and the Arrow protocol. But now it works. It is 20 times faster than current full-copy rpolars `pl$DataFrame()` [The implementation is very analogues to py_polars](https://github.com/pola-rs/r-polars/blob/f300f8d9cdafba7a525526bee2909c4e54c609ee/src/rust/src/arrow_interop/to_rust.rs#L75) it calls arrow:::ExportArray for every chunk of every column. If chunks are very small, it might slow down a bit.

right now import speed is around 21ms for 600k row x 19 columns.

```R

> library(rpolars)
> library(arrow)
> library(nycflights13)
> 
> 
> rbr = as_record_batch_reader(nycflights13::flights)
> big_arrow_table = do.call(rbind,lapply(1:2, \(x) arrow::arrow_table(nycflights13::flights)))
> rbr = as_record_batch_reader(big_arrow_table)
> 
> dim(big_arrow_table)
[1] 673552     19
> 
> # via arrow API
> system.time({df = rpolars:::rb_list_to_df(rbr$batches(),rbr$schema$names)})
   user  system elapsed 
  0.020   0.001   0.022 
> 
> big_df = as.data.frame(big_arrow_table)
> 
> # via r-polars conversion full copy
> system.time({df_simple = pl$DataFrame(big_df)})
   user  system elapsed 
  0.381   0.007   0.387 
> 
```

**Comment by eddelbuettel** [comment]
Nice. And you immediatly went for batches.

**Comment by sorhawell** [comment]
For future reference. This implementation calls via low-level ExportArray for each chunk (contiguous array of mem). To speed up further likely use a high-level stream interface, to avoid calling via R for each chunk. It should be something rust arrow2 and R Arrow both supports.

**Comment by kylebarron** [comment]
> uhh I hit a steep bump on my learning path on pointer magic and the Arrow protocol. But now it works. It is 20 times faster than current full-copy rpolars `pl$DataFrame()`

The perfect use case for the C data interface!

> If chunks are very small, it might slow down a bit.

IIRC py-polars tends to rechunk the data to avoid having lots of small batches

**Comment by sorhawell** [comment]
found another 2x speed-up by doing exactly as in py-polars
200ms for 8M rows and 20 mixed strings and ints columns.

> IIRC py-polars tends to rechunk the data to avoid having lots of small batches

yeah in the end it will likely get rechunked. I was concerned when importing every single chunk before the rechunking, that there would be considerable overhead. However, I tried benchmark a input table of 500 chunks versus 20, and the latter was only 16% faster, so probably as good as it gets.

**Comment by kylebarron** [comment]
> use a high-level stream interface, to avoid calling via R for each chunk. It should be something rust arrow2 and R Arrow both supports

Also just to make sure you're aware, this seems like a great use case for the [Arrow C Stream interface](https://arrow.apache.org/docs/format/CStreamInterface.html). arrow2 supports that [here](https://github.com/jorgecarleitao/arrow2/blob/main/src/ffi/stream.rs) and I have an example of using that [here](https://github.com/georust/gdal/blob/1dbc60215033caee1f99d933ae11354f70bc5f0e/examples/read_ogr_arrow.rs). I'm not familiar with R arrow but nanoarrow says it supports that interface

**Comment by sorhawell** [comment]
@kylebarron  many thx for examples it was helpful. 

I got streaming of record-batches from R-arrow to Arrow2 to work, however I see no option in R-arrow or py-arrow to just stream a chunked array as is without turning it into row-wise records/structs.

I made a question on SO about it:
[Can I produce a chunked-array stream from py-arrow and/or r-arrow and export it to rust?](https://stackoverflow.com/questions/75694639/can-i-produce-a-chunked-array-stream-from-py-arrow-and-or-r-arrow-and-export-it)

**Comment by sorhawell** [comment]
@eddelbuettel  and @kylebarron  many thanks for input
`pl$from_arrow()` has been implemented now

There was little fun unexpected spin-off, in an upcomming version of rpolars, it is slightly faster to create an r-arrow `Table` via r-polars `DataFrame`+`nanoarrow` because r-polars can read from R memory multi-threaded (some AltRep not supported ... ).

``` r
library(rpolars)
library(arrow)
#> 
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#> 
#>     timestamp
library(nycflights13)
library(nanoarrow)
library(bench)
big_df =  do.call(rbind,lapply(1:25, \(x) nycflights13::flights))
x = bench::mark(
  r_polars = pl$DataFrame(big_df,parallel = TRUE),
  r_to_polars_to_arrow = as_arrow_table(pl$DataFrame(big_df,parallel = TRUE)),
  r_to_arrow = as_arrow_table(big_df),
  check = FALSE
)
print(x)
#> # A tibble: 3 × 13
#>   expression              min median itr/s…¹ mem_a…² gc/se…³ n_itr  n_gc total…⁴
#>   <bch:expr>           <bch:> <bch:>   <dbl> <bch:b>   <dbl> <int> <dbl> <bch:t>
#> 1 r_polars              644ms  644ms    1.55  64.6MB       0     1     0   644ms
#> 2 r_to_polars_to_arrow  677ms  677ms    1.48  65.9MB       0     1     0   677ms
#> 3 r_to_arrow            987ms  987ms    1.01  93.9KB       0     1     0   987ms
#> # … with 4 more variables: result <list>, memory <list>, time <list>,
#> #   gc <list>, and abbreviated variable names ¹​`itr/sec`, ²​mem_alloc,
#> #   ³​`gc/sec`, ⁴​total_time
```

<sup>Created on 2023-03-14 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
