### ISSUE TITLE
Rename `pl$polars_*` to `polars_*`

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#653]
Something like `pl$polars_info()` looks very strange considering `pl` is short for `polars` (e.g. `import polars as pl`).
Another way is renaming `pl$polars_*` to `pl$*`, but considering that there is a low possibility that names of functions with `polars_` in the prefix will collide, I feel that naming it `polars_*` makes more sense than placing it under `pl`.

@sorhawell @etiennebacher Thoughts?

**Comment by sorhawell** [comment]
I see your point, that is redundant.

I personally would favor `pl$info()`. 

The initial idea of `pl$` was to both mimic `pl.` syntax in python but also as a little push back to R community, which uses `import * from xyz` aka. `library(xyz)` which leads to name space collisions across packages.

I was thinking of `pl´as "the entire public api". A user may be looking for something with `info...` but would have to search both `pl$`and `polars::` to find it. Then to make it easier for the user,  all content of `pl$` could be moved directly into `polars::`. But then there will be a big name space collision if the user does `library(polars)`.

**Comment by eitsupi** [comment]
I think I understand your intent, but since `polars.info` doesn't exist in the Python package, I'm wondering if there's a need to push something like that into `pl`.

Since it is not obvious to users how to display the help page for things under `pl`, I believe that it is more useful if some of the basic functions are not under `pl`, from the perspective of being able to quickly open the help page.

**Comment by etiennebacher** [comment]
I agree it would be easier to discover if it was `polars::polars_info()`

**Comment by eitsupi** [comment]
Thank both.
Let's deprecate something `pl$polars_info()` and rename it to `polars_info()`.
