### ISSUE TITLE
src/rust/Cargo.lock should not be checked in 

### ISSUE THREAD

**Issue by ssh352** [pola-rs/r-polars#666]
per the documentation here
https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/cargo/guide/cargo-toml-vs-cargo-lock.html

Please take a look, thanks

**Comment by eitsupi** [comment]
If the lock file is missing, the patch version cannot be fixed and the package may be broken, so the lock file must be checked in.

**Comment by ssh352** [comment]
> If the lock file is missing, the patch version cannot be fixed and the package may be broken, so the lock file must be checked in.

Thanks for the explanation. Why not put the version number explicitly in Cargo.toml instead? Cargo.lock is automatically generated when you do cargo build.

**Comment by eitsupi** [comment]
> Thanks for the explanation. Why not put the version number explicitly in Cargo.toml instead? Cargo.lock is automatically generated when you do cargo build.

It is not possible to fix the patch version in Cargo.toml.
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html
