### ISSUE TITLE
`pl$from_arrow()` v.s. `as_polars_df()`

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#677]
I suspect that things like the `pl$from_arrow()` function are due to Python syntax/conventions and should not be brought into R.
In R it is common to handle such things by dispatching using the S3 (or S7 in the future) method, and I think we can eliminate `pl$from_arrow` in favor of `as_polars_df.Table`.

Related to #497

**Comment by etiennebacher** [comment]
We use `pl$from_arrow()` a couple of times internally. Do you want to replace those calls with an alternative? If not, we could just let it exist for people who want a good symmetry with the python interface

**Comment by eitsupi** [comment]
> We use `pl$from_arrow()` a couple of times internally. Do you want to replace those calls with an alternative?

As I understand, the only function calling `pl$from_arrow` is `as_polars_df`.

When I search for it, it seems to be used in the following place, but I don't know if this is actually used.
This function is part of `pl$from_arrow`, so it is a recursive call.

https://github.com/pola-rs/r-polars/blob/89fe7196422a5477307db1015dbd139ad323158c/R/construction.R#L155-L161

**Comment by etiennebacher** [comment]
Can this be closed?

**Comment by eitsupi** [comment]
I think we can close this after deprecating `pl$from_arrow` (it's a bit tedious as there is test porting)
