### ISSUE TITLE
Remove `GroupBy` (and others) in favor of `LazyGroupBy`?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#696]
> While reading the Rust source code, I noticed that aggregate calculation with GroupBy has been deprecated for years (pola-rs/polars#4946).
>Perhaps at some point, given the current complexity, we may as well remove GroupBy and use only LazyGroupBy.
https://docs.rs/polars/0.36.2/polars/prelude/struct.GroupBy.html

_Originally posted by @eitsupi in https://github.com/pola-rs/r-polars/issues/694#issuecomment-1890540599_

**Comment by eitsupi** [comment]
My point was that it may be better to remove the eager group by in favor of lazy API, as the additional classes make it quite confusing for beginners.
py-polars has three classes to reproduce the group by in the eager API It has three classes to reproduce group by in the eager API, but two (rolling and dynamic) are not shown in the documentation.......

**Comment by etiennebacher** [comment]
I think we're documenting this the right way and that the python-polars API docs should be updated. In their [DataFramereference page](https://docs.pola.rs/py-polars/html/reference/dataframe/index.html), they should add the categories `DynamicGroupBy` and `RollingGroupBy`, just like they have a category `GroupBy`.

Those are not identical: one can apply `.first()` on a `GroupBy` object, but not on a `RollingGroupBy` object for instance.

**Comment by eitsupi** [comment]
This does not seem to be a problem since this is the same implementation approach as Python Polars.
