### ISSUE TITLE
many rs files are not rustfmt ed

### ISSUE THREAD

**Issue by ssh352** [pola-rs/r-polars#747]
for example running rustfmt with default configuration on 
src/rust/src/rdataframe/read_parquet.rs generates a diff. 

actually running task build-rust generates lots of format diff.

also should I use Rstudio or styleR to format the R code? should I use default configuration for both?

Please advise. Thanks!

**Comment by etiennebacher** [comment]
> also should I use Rstudio or styleR to format the R code? should I use default configuration for both?

Run `task format-r` (or `task format-rs` for Rust files) in the terminal

**Comment by ssh352** [comment]
Thanks for help. The task tool is very nice. I'll use both commands to format the code accordingly.

 I used rustc latest nightly, however I have a .rustfmt.toml in my home dir which I forgot. 

Is it possible we have a .rustfmt.toml in project root so user home .rustfmt.toml won't interfere?

**Comment by eitsupi** [comment]
> Is it possible we have a .rustfmt.toml in project root so user home .rustfmt.toml won't interfere?

The version of rust-toolchain is defined here. Does that file in the user home take precedence even if default is specified in the command?

https://github.com/pola-rs/r-polars/blob/d2d3dafb2f60860eadd70be0f6edd520419d8aa4/DESCRIPTION#L121

**Comment by eitsupi** [comment]
Oh, sorry. You are talking about the formatter settings, not the toolchain. It would make sense to add that file.
