### ISSUE TITLE
Should `to_data_frame()` keep existing attributes?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#759]
I think we should keep attributes of a `DataFrame` that don't have names that will be overwritten by the conversion to `data.frame` (e.g `row.names`).

Here, the attribute `foobar` disappears:
``` r
library(polars)

test = pl$DataFrame(a = 1)
attributes(test)$foobar <- "hello there"

attributes(test)
#> $class
#> [1] "RPolarsDataFrame"
#> 
#> $foobar
#> [1] "hello there"
attributes(test$to_data_frame())
#> $names
#> [1] "a"
#> 
#> $row.names
#> [1] 1
#> 
#> $class
#> [1] "data.frame"
attributes(test$to_list())
#> $names
#> [1] "a"
```

**Comment by etiennebacher** [comment]
I just had a case when running tests in `tidypolars`. Basically I wanted to check that group attributes that I add to a `DataFrame` are correctly removed by `ungroup()`. Problem is that my test function automatically collects the `DataFrame` and I lost all the attributes, so it didn't make sense to check if attributes were removed or not by `ungroup()` since they were dropped anyway. 

Not sure it's clear, but it's a corner case and it was easy to bypass. I was just wondering if this was something we should support. I don't have more usecases in mind for now and I don't know what other packages do

**Comment by eitsupi** [comment]
I think I wrote it somewhere before, but `tidypolars` should create a separate class with additional attributes, like `dtplyr` has `lazy_dt` instead of `data.table`, and `arrow` has `arrow_dplyr_query` instead of `Table`.

I think you should define it and not add the attribute to the existing RPolarsDataFrame.

**Comment by etiennebacher** [comment]
Yeah I should have something like that
