### ISSUE TITLE
pl.read_csv() fails to read full file and completes operation without error message; cannot read more than 2,225 lines?

### ISSUE THREAD

**Issue by frasertajima** [pola-rs/r-polars#778]
I have a Kindle clipping notebook that reads a text file:
```
import polars as pl
#import numpy as np
import cupy as np
colspecs = [(None, None)]
kindle_clipping_file="My Clippings scribe.txt"
data = pl.read_csv(kindle_clipping_file, columns=[0], has_header=False)
with pl.Config(fmt_str_lengths=300, tbl_rows=30):
    display(data)
```
On a file with 10,000 plus lines, it only reads 2,225 lines but it does so without indicating any error or failure to read the full file (which is very undesirable). 
![Screenshot from 2024-02-05 18-34-45](https://github.com/pola-rs/r-polars/assets/69366820/0e50ec08-977d-4f45-b54d-1985d4316265)

In Pandas, it reads the full  10,574 lines on the same file (and I manually confirmed that pandas reads in the entire file to the end). I can read the same file in pandas first and then convert to polars so it works fully:

```
import pandas as pd
import polars as pl
import cupy as np
colspecs = [(None, None)]
kindle_clipping_file="My Clippings scribe.txt"

# Read the fixed-width file with pandas
# using polars.read_csv() stops reading after 2,225 rows???
# need to pd.read_fwf then convert to polars to ensure at 10,000 rows read in
datapd = pd.read_fwf(kindle_clipping_file, colspecs=colspecs, header=None)

# Convert the pandas DataFrame to a Polars DataFrame
data = pl.from_pandas(datapd)
# must rename pandas column 0 to column_1 for the next section below
data = data.rename({"0": "column_1"})
#data = pl.read_csv(kindle_clipping_file, columns=[0], has_header=False)
with pl.Config(fmt_str_lengths=300, tbl_rows=20):
    display(data)
```
![Screenshot from 2024-02-05 18-34-27](https://github.com/pola-rs/r-polars/assets/69366820/639c86d4-f947-407d-88a0-0edb2384e313)

My entire notebook is here:  https://github.com/frasertajima/kindle_clippings/blob/main/Kindle_scribe_my_clippings_reader_polars_cupy2.ipynb

I assume I am doing something wrong in Polars but did not notice when working with smaller files. Is this a polars issue or me?

**Comment by eitsupi** [comment]
I think you have opened this issue in a wrong repo.
Please go to <https://github.com/pola-rs/polars/issues/new/choose>.
