### ISSUE TITLE
Should package name be “polars”?

### ISSUE THREAD

**Issue by grantmcdermott** [pola-rs/r-polars#82]
As a general principle, I think that repo names should correspond exactly to package names. Unfortunately, there’s a subtle hyphen in the way here, which IMO is unnecessary and potentially confusing for users who are trying to install from source.

_TL;DR_ Consider moving the repo from `pola-rs/r-polars` to `pola-rs/rpolars` (i.e., drop the second hyphen).

**Comment by sorhawell** [comment]
@grantmcdermott  you're right it is a bit confusing as of now.

Current naming within the polars organization are (project; package)
py-polars; polars
rust-polars; polars
nodejs-polars; ?
r-polars; rpolars

I don't like currently writing docs and have to choose between r-polars and rpolars knowing most readers will not see the difference.
I was concidering to also rename the R package just polars. This would also be more alligned with the r-arrow;arrow naming standard.

What do you think of that?

**Comment by grantmcdermott** [comment]
Thanks both. I really like @eitsupi's first suggestion: Use  repo: `pola-rs/r-polars`, package: `polars`. 

This would obviously be a breaking change, since the package name will be changing. But I personally think it's worth it to establish long-term consistency. (And, as @sorhawell says, make it easier to maintain docs!)

**Comment by vincentarelbundock** [comment]
I think this can be closed via the recent PR merge, no?

**Comment by eitsupi** [comment]
Yes, let's close.
