### ISSUE TITLE
Should `as.data.frame()` on `LazyFrame` automatically collect the data?

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#829]
I'm not a big fan of `as.data.frame()` automatically collecting the LazyFrame under the hood. I'd rather require the user to be explicit and call `collect()` so that the only purpose of `as.data.frame()` is to convert collected data to an R data.frame.

@eitsupi what do you think about this? I wanted to add a custom method for `as.data.frame()` in `tidypolars` (https://github.com/etiennebacher/tidypolars/issues/87) but maybe we can change this behavior here instead?

**Comment by eitsupi** [comment]
The tbl_lazy is for simulation, not the actual DB connection.
The actual custom class for dbplyr is tbl_sql

**Comment by eitsupi** [comment]
I should also add that the arrow package did not initially have a method of the as.data.frame function for the dataset class, etc., but it has been added at the request of users.
apache/arrow#30938

We should learn from history.

**Comment by etiennebacher** [comment]
Good to know, I don't have much working experience with all those packages so thanks for the explanations / links.

**Comment by eitsupi** [comment]
I think I've done quite a bit of research on these packages, so feel free to ask if you don't understand anything.

**Comment by eitsupi** [comment]
As a point of clarification, tbl_lazy is a class for checking how SQL is generated and cannot actually perform any calculations because the backend does not exist.
In other words, `dplyr::collect` also does not work, and it is impossible to convert it to a data frame.
