### ISSUE TITLE
Improvement: Use pkgdown development auto mode

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#85]
https://pkgdown.r-lib.org/articles/how-to-update-released-site.html?q=Devel#automatic-development-mode

Should replace current is_release logic. Above allows to both build Dev and Release docs.

**Comment by eitsupi** [comment]
If you use this, I recommend using the function [`usethis::use_version()` and `usethis::use_dev_version()`](https://usethis.r-lib.org/reference/use_version.html) to increment the version number before and after releasing.
