### ISSUE TITLE
Remove the `eager` argument of `pl$date_range()` and `pl$struct()`

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#880]
I think it would be better to remove it and simplify it, since it simply allows the subsequent `$to_series()` to be omitted.

**Comment by etiennebacher** [comment]
I don't see why we would depart from python polars here. That would just remove an if condition and I don't see other benefits to making this breaking change.

**Comment by eitsupi** [comment]
> I don't see why we would depart from python polars here. That would just remove an if condition and I don't see other benefits to making this breaking change.

Unlike the Python world, where type hints work more or less the same way, the fact that the return type is unspecified in the R world is a very big disadvantage.

**Comment by eitsupi** [comment]
In addition, in R, it is easy to convert to Series using the `to_series()` method, which is not possible in Python.

**Comment by etiennebacher** [comment]
> Unlike the Python world, where type hints work more or less the same way, the fact that the return type is unspecified in the R world is a very big disadvantage.

I don't understand this argument. Sorry if I'm missing sth obvious but why would removing `eager` change anything to this?

**Comment by eitsupi** [comment]
> I don't understand this argument. Sorry if I'm missing sth obvious but why would removing `eager` change anything to this?

These functions return completely different return values for `eager = TRUE` and `eager = FALSE`.
Using such functions makes it difficult to predict what will happen and makes the code less readable.

**Comment by etiennebacher** [comment]
Ok, I can take care of this one if you want

**Comment by eitsupi** [comment]
Thank you for your understanding.
I think it is well known in the software world that one function should do one thing which is part of the UNIX philosophy.
(As an aside, other amazing things I have seen recently are `polars.first()` and `polars.last()` which do completely different things, returning one row or one column depending on their arguments.)
