### ISSUE TITLE
Add `:` generic methods

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#881]
I was wondering if it could be mapped to `int_range`.
https://docs.rs/polars/0.38.1/polars/prelude/fn.int_range.html

**Comment by etiennebacher** [comment]
I don't think it's possible since `:` doesn't seem to be a generic:

``` r
sloop::is_s3_generic("+")
#> [1] TRUE

sloop::is_s3_generic(":")
#> [1] FALSE
```
If it was then I'd be ok with that. 

Overall I think we should rework the `range`-related functions. Currently we have `pl$date_range()` but not `pl$date_ranges()`, and we don't have the `int_range()` functions.

**Comment by eitsupi** [comment]
Oh, sorry, I must have misunderstood. The `:` I saw was from the bit64 package......
