### ISSUE TITLE
Release on https://r-releases.r-universe.dev/ ?

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#888]
See <https://github.com/r-releases/help> for details.

We are currently distributing the latest release version in the R-universe of the rpolars organization, but it may be worth distributing there as well.

**Comment by etiennebacher** [comment]
Sounds interesting, I'm ok to release there as well but it's quite new so let's wait a bit before putting this in the README maybe?

**Comment by eitsupi** [comment]
r-releases/r-releases#58
