### ISSUE TITLE
Edit README.Rmd

### ISSUE THREAD

**Issue by grantmcdermott** [pola-rs/r-polars#91]
Hey @sorhawell I just saw https://github.com/pola-rs/r-polars/commit/12ea79c86c6b6b69d108bec62cf80542b5da0aa9. A very minor comment is that, if you want to stick with the workflow I introduced in #81, it's best to edit the README.Rmd file instead and then knit the resulting .md version from this (i.e., rather than editing the README.md directly).

Obviously, you don't need to stick with going through Rmarkdown. But I personally quite like it, as it auto produces the code etc.

**Comment by sorhawell** [comment]
Good point. That was a blunder.

**Comment by sorhawell** [comment]
windows linker warning not related to readme I hope :)  likely new R version. Filter away linker warning and track that in  #93

**Comment by eitsupi** [comment]
It is also worth considering simplifying the workflow by using Makefile, Taskfile, justfile, etc.
https://github.com/pola-rs/polars seems using Makefiles.
