### ISSUE TITLE
Move API document website to this repository's GitHub pages

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#932]
I don't know if there is any reason not to move.
The workflow is currently complicated to push to another repository and @sorhawell's personal ssh key is stored in the GitHub secret.

**Comment by etiennebacher** [comment]
Fine for me as long as we have a redirect from rpolars.github.io to pola-rs.github.io (never done this but I guess it's not too hard). It would also be cool to be listed in the [API reference](https://docs.pola.rs/api/) page of the official polars docs.

**Comment by eitsupi** [comment]
It seems that redirection in GitHub pages is very easy, only create a CNAME file.
<https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages>

**Comment by eitsupi** [comment]
I noticed that redirects by CNAME are only for domain names, so I set up a redirect using https://github.com/jekyll/jekyll-redirect-from.
