### ISSUE TITLE
[DISC] Import the `rlang` package

### ISSUE THREAD

**Issue by eitsupi** [pola-rs/r-polars#942]
Related to #939 (and potentially #367)

With limited development resources, I don't want to reinvent the wheel any further with what `rlang` has to offer.
I think there used to be value in not having dependencies to install binary packages on GitHub releases, but I don't see much value in not having dependencies now that installing from the R-universe works so well.

`rlang` is very widely used and `rlang` itself is a very small dependency since it does not depend on any other package.

## Pros

- Features such as trailing commas and dot checks will be available.

## Cons

- This will be the first external required dependency.

---

@etiennebacher @sorhawell @vincentarelbundock @grantmcdermott @Sicheng-Pan Thoughts?

**Comment by lorenzwalthert** [comment]
Or use https://github.com/wch/staticimports?

**Comment by eitsupi** [comment]
Recently to enforce named arguments with `...` is increasingly used, and given the frequency with which Polars change argument names, it would be worthwhile to use the `rlang::check_dots_empty()` function to check arguments to reduce implicit failures for the user.

I am not sure how much emphasis on no dependencies is worth.

**Comment by eitsupi** [comment]
Closing in favor of #1152
