### ISSUE TITLE
Feature request: add `extract_groups` for str methods

### ISSUE THREAD

**Issue by Yunuuuu** [pola-rs/r-polars#975]
Extract multiple groups at once: https://github.com/pola-rs/polars/pull/10179

**Comment by etiennebacher** [comment]
@george-wood or @Yunuuuu, do you want to implement this one?

I can do it otherwise

**Comment by Yunuuuu** [comment]
I can write R code but have no knowledge with `rust` language. I think I can write some unit tests or fix Docs.

**Comment by george-wood** [comment]
I won't be able to work on this in the next month or so, but I can implement this (or another feature) if it's still on the to-do list then.

@Yunuuuu My understanding is that, with feature additions to `r-polars` such as this one, there's usually minimal interaction with the rust implementation. @etiennebacher and @eitsupi please correct me if I am wrong.

**Comment by Yunuuuu** [comment]
Thanks to @george-wood and @etiennebacher, I am currently studying the underlying code of the polars package. I have recently examined the implementation of the `$str$extract_groups` method (thank you @etiennebacher for quickly implementing it), and I have discovered that it only utilizes a small amount of Rust code. I decided to transition my project from `data.table` to `polars` due to the large size of the data I am working with. If I come across any missing features, I will try to learn and implement them myself.

I really like the `$collect_in_background` method, as it allows us to run parallel operations directly. I have written the following code to use this feature. I hope someone finds it helpful:

```r
#' @param .x A series object.
#' @param .fn Must call `$collect_in_background()` method.
#' @keywords internal
#' @importFrom polars pl
#' @noRd
polars_lapply <- function(.x, .fn, ..., .progress, .threads = 2L) {
    # .threads <- min(as.integer(.threads), pl$thread_pool_size())
    poos_size <- max(.threads, 1L)
    n <- .x$len()
    bar <- do.call(cli::cli_progress_bar, c(
        .progress, list(total = n, clear = FALSE)
    ))
    results <- vector("list", n)
    # pools: store the index of result
    # NA means this pool can be used
    pools <- rep_len(NA_integer_, poos_size)
    i <- pool <- 1L
    while (i <= n || !all(is.na(pools))) {
        handle_index <- .subset(pools, pool)
        # if i > n, we skip add task
        if (i <= n && is.na(handle_index)) {
            # this pool can be used, we add task into this pool
            # `.fn()` must return with `$collect_in_background()` method
            # For Series, cannot subset with `[[`
            results[[i]] <- .fn(.x$slice(i - 1L, 1L), ...)
            pools[pool] <- i
            i <- i + 1L
        }

        # if there is a task in this pool
        # we check if we can release this pool
        if (!is.na(handle_index)) {
            polars_handle <- .subset2(results, handle_index)
            if (polars_handle$is_finished()) {
                # collect result from this pool and release this pool
                results[[handle_index]] <- polars_handle$join()
                pools[pool] <- NA_integer_
                cli::cli_progress_update(inc = 1L, id = bar)

                # this pool has been released, so we directly
                # step into next cycle and re-use this pool
                if (i <= n) next
            }
        }

        # search next pool
        if (pool == poos_size) {
            pool <- 1L
        } else {
            pool <- pool + 1L
        }
    }
    results
}
```
